<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tutorial 3 ANOVA | Statistics Tutorials &amp; Templates</title>
  <meta name="description" content="Tutorial 3 ANOVA | Statistics Tutorials &amp; Templates" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Tutorial 3 ANOVA | Statistics Tutorials &amp; Templates" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tutorial 3 ANOVA | Statistics Tutorials &amp; Templates" />
  
  
  

<meta name="author" content="Dr. F.J. Rodenburg © 2022" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chi-squared-test.html"/>
<link rel="next" href="twowaymultiway.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics Tutorials & Templates</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>1</b> T-Test</a>
<ul>
<li class="chapter" data-level="1.1" data-path="t-test.html"><a href="t-test.html#read-t"><i class="fa fa-check"></i><b>1.1</b> Read the Data into R</a></li>
<li class="chapter" data-level="1.2" data-path="t-test.html"><a href="t-test.html#vis-t"><i class="fa fa-check"></i><b>1.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="1.3" data-path="t-test.html"><a href="t-test.html#choose-an-appropriate-t-test"><i class="fa fa-check"></i><b>1.3</b> Choose an Appropriate T-Test</a></li>
<li class="chapter" data-level="1.4" data-path="t-test.html"><a href="t-test.html#results-t"><i class="fa fa-check"></i><b>1.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="1.5" data-path="t-test.html"><a href="t-test.html#incorporating-this-in-a-paper"><i class="fa fa-check"></i><b>1.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chi-squared-test.html"><a href="chi-squared-test.html"><i class="fa fa-check"></i><b>2</b> Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chi-squared-test.html"><a href="chi-squared-test.html#read-the-data-into-r"><i class="fa fa-check"></i><b>2.1</b> Read the Data into R</a></li>
<li class="chapter" data-level="2.2" data-path="chi-squared-test.html"><a href="chi-squared-test.html#vis-chi"><i class="fa fa-check"></i><b>2.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="2.3" data-path="chi-squared-test.html"><a href="chi-squared-test.html#conduct-a-chi-squared-test"><i class="fa fa-check"></i><b>2.3</b> Conduct a Chi-Squared Test</a></li>
<li class="chapter" data-level="2.4" data-path="chi-squared-test.html"><a href="chi-squared-test.html#results-chi"><i class="fa fa-check"></i><b>2.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="2.5" data-path="chi-squared-test.html"><a href="chi-squared-test.html#incorporating-this-in-a-paper-1"><i class="fa fa-check"></i><b>2.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>3</b> ANOVA</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova.html"><a href="anova.html#read-ANOVA"><i class="fa fa-check"></i><b>3.1</b> Read the Data into R</a>
<ul>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#reordering-a-factor"><i class="fa fa-check"></i>Reordering a Factor</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="anova.html"><a href="anova.html#vis-ANOVA"><i class="fa fa-check"></i><b>3.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="3.3" data-path="anova.html"><a href="anova.html#analyze-the-data"><i class="fa fa-check"></i><b>3.3</b> Analyze the Data</a>
<ul>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#fit-the-model"><i class="fa fa-check"></i>Fit the Model</a></li>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#perform-diagnostics"><i class="fa fa-check"></i>Perform Diagnostics</a></li>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#outlierexample"><i class="fa fa-check"></i>Dealing with Potential Outliers</a></li>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#perform-an-omnibus-test"><i class="fa fa-check"></i>Perform an Omnibus Test</a></li>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#perform-a-post-hoc-analysis"><i class="fa fa-check"></i>Perform a Post Hoc Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="anova.html"><a href="anova.html#results-ANOVA"><i class="fa fa-check"></i><b>3.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="3.5" data-path="anova.html"><a href="anova.html#incorporating-this-in-a-paper-2"><i class="fa fa-check"></i><b>3.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="twowaymultiway.html"><a href="twowaymultiway.html"><i class="fa fa-check"></i><b>4</b> Two-Way &amp; Multi-Way ANOVA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="twowaymultiway.html"><a href="twowaymultiway.html#read-ANOVA2"><i class="fa fa-check"></i><b>4.1</b> Read the Data into R</a>
<ul>
<li class="chapter" data-level="" data-path="twowaymultiway.html"><a href="twowaymultiway.html#reordering-a-factor-1"><i class="fa fa-check"></i>Reordering a Factor</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="twowaymultiway.html"><a href="twowaymultiway.html#vis-ANOVA2"><i class="fa fa-check"></i><b>4.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="4.3" data-path="twowaymultiway.html"><a href="twowaymultiway.html#analyze-the-data-1"><i class="fa fa-check"></i><b>4.3</b> Analyze the Data</a>
<ul>
<li class="chapter" data-level="" data-path="twowaymultiway.html"><a href="twowaymultiway.html#fit-the-model-1"><i class="fa fa-check"></i>Fit the Model</a></li>
<li class="chapter" data-level="" data-path="twowaymultiway.html"><a href="twowaymultiway.html#perform-diagnostics-1"><i class="fa fa-check"></i>Perform Diagnostics</a></li>
<li class="chapter" data-level="" data-path="twowaymultiway.html"><a href="twowaymultiway.html#dealing-with-potential-outliers"><i class="fa fa-check"></i>Dealing with Potential Outliers</a></li>
<li class="chapter" data-level="" data-path="twowaymultiway.html"><a href="twowaymultiway.html#perform-an-omnibus-test-1"><i class="fa fa-check"></i>Perform an Omnibus Test</a></li>
<li class="chapter" data-level="" data-path="twowaymultiway.html"><a href="twowaymultiway.html#perform-a-post-hoc-analysis-1"><i class="fa fa-check"></i>Perform a Post Hoc Analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="twowaymultiway.html"><a href="twowaymultiway.html#results-ANOVA2"><i class="fa fa-check"></i><b>4.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="4.5" data-path="twowaymultiway.html"><a href="twowaymultiway.html#incorporating-this-in-a-paper-3"><i class="fa fa-check"></i><b>4.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="linear-model.html"><a href="linear-model.html"><i class="fa fa-check"></i><b>5</b> Linear Model</a></li>
<li class="chapter" data-level="6" data-path="generalized-linear-model.html"><a href="generalized-linear-model.html"><i class="fa fa-check"></i><b>6</b> Generalized Linear Model</a></li>
<li class="chapter" data-level="7" data-path="mixed-model.html"><a href="mixed-model.html"><i class="fa fa-check"></i><b>7</b> Mixed Model</a></li>
<li class="chapter" data-level="8" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>8</b> GLMM</a></li>
<li class="chapter" data-level="9" data-path="exploration-pca.html"><a href="exploration-pca.html"><i class="fa fa-check"></i><b>9</b> Exploration: PCA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="exploration-pca.html"><a href="exploration-pca.html#read-the-data-into-r-1"><i class="fa fa-check"></i><b>9.1</b> Read the Data into R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reading-storing-data.html"><a href="reading-storing-data.html"><i class="fa fa-check"></i><b>10</b> Reading &amp; Storing Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="reading-storing-data.html"><a href="reading-storing-data.html#tidy"><i class="fa fa-check"></i><b>10.1</b> Tidy Format</a></li>
<li class="chapter" data-level="10.2" data-path="reading-storing-data.html"><a href="reading-storing-data.html#separate-data-entry-analysis"><i class="fa fa-check"></i><b>10.2</b> Separate Data Entry &amp; Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="reading-storing-data.html"><a href="reading-storing-data.html#excel-is-not-statistical-software"><i class="fa fa-check"></i>Excel Is Not Statistical Software</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="reading-storing-data.html"><a href="reading-storing-data.html#metadata"><i class="fa fa-check"></i><b>10.3</b> Meta Data</a></li>
<li class="chapter" data-level="10.4" data-path="reading-storing-data.html"><a href="reading-storing-data.html#csv"><i class="fa fa-check"></i><b>10.4</b> Reading Data as CSV</a></li>
<li class="chapter" data-level="10.5" data-path="reading-storing-data.html"><a href="reading-storing-data.html#Excel"><i class="fa fa-check"></i><b>10.5</b> Reading Data from Excel</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a>
<ul>
<li class="chapter" data-level="10.6" data-path="references.html"><a href="references.html#quarto"><i class="fa fa-check"></i><b>10.6</b> Quarto</a></li>
<li class="chapter" data-level="10.7" data-path="references.html"><a href="references.html#running-code"><i class="fa fa-check"></i><b>10.7</b> Running Code</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics Tutorials &amp; Templates</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Tutorial 3</span> ANOVA<a href="anova.html#anova" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><small><i>A method test to <b>compare any number of means</b> to see if they differ significantly. Observations are assumed to be <strong>independent</strong>, deviations from the group means are assumed to follow a <strong>normal distribution</strong>, and groups are assumed to have <strong>equal variance</strong>.</i></small></p>
<hr />
<details>
<summary>
Summary
</summary>
<ol style="list-style-type: decimal">
<li><a href="https://youtu.be/BGUqZc-Pb8w">Read the data into R <font color = "red"><i class="fa fa-youtube-play"></i></font></a>;</li>
<li>Visualize the data;</li>
<li>Fit an ANOVA:
<ul>
<li>Perform visual diagnostics to look for deviations from the assumptions;</li>
<li>Perform an omnibus test if the assumptions appear reasonable;</li>
<li>Perform a post-hoc test if the omnibus test was significant;</li>
</ul></li>
<li>Report a conclusion;</li>
<li>Incorporating this in scientific literature.</li>
</ol>
</details>
<p>
<p>Download the template <a href="files/template-ANOVA.qmd">here <i class="fa fa-download"></i></a> and the required data set <a href="data/three-groups.csv">here <i class="fa fa-download"></i></a>.</p>
<div id="read-ANOVA" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Read the Data into R<a href="anova.html#read-ANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I recommend saving data as <a href="https://youtu.be/BGUqZc-Pb8w">comma-separated values (CSV)</a>. If you prefer reading data directly from Excel, have a look <a href="reading-storing-data.html#Excel">here</a>.</p>
<details>
<summary>
Details
</summary>
<ul>
<li>Save the data in a folder;</li>
<li>Open RStudio and create a new R markdown or Quarto file; <small>(<strong>File</strong> &gt; <strong>New File</strong> &gt; <strong>R Markdown</strong>)</small></li>
<li>Save your R markdown file to the same location as the data;</li>
<li>Set working directory to source file location. <small>(<strong>Session</strong> &gt; <strong>Set Working Directory</strong> &gt; <strong>To Source File Location</strong>)</small></li>
</ul>
</details>
<p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="anova.html#cb1-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;three-groups.csv&quot;</span>)</span></code></pre></div>
<p>Did that work? There are several ways to check:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="anova.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DF)</span>
<span id="cb2-2"><a href="anova.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DF)</span>
<span id="cb2-3"><a href="anova.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(DF)</span></code></pre></div>
<details>
<summary>
Explanation of the output
</summary>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="anova.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DF)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    90 obs. of  4 variables:
##  $ SBP      : int  122 119 120 129 127 118 120 124 126 117 ...
##  $ treatment: chr  &quot;thiazide&quot; &quot;thiazide&quot; &quot;thiazide&quot; &quot;thiazide&quot; ...
##  $ age      : int  32 34 36 41 35 38 36 33 39 32 ...
##  $ sex      : chr  &quot;female&quot; &quot;female&quot; &quot;female&quot; &quot;male&quot; ...</code></pre>
<p>This command shows the structure of the data. It is a data frame with <span class="math inline">\(n = 90\)</span> observations of 4 variables. <code>SBP</code> and age are stored as integers (<code>int</code>), while <code>treatment</code> and <code>sex</code> are stored character vectors (<code>chr</code>).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="anova.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DF)</span></code></pre></div>
<pre><code>##       SBP         treatment              age            sex           
##  Min.   :114.0   Length:90          Min.   :23.00   Length:90         
##  1st Qu.:122.0   Class :character   1st Qu.:32.00   Class :character  
##  Median :127.0   Mode  :character   Median :35.00   Mode  :character  
##  Mean   :131.5                      Mean   :35.69                     
##  3rd Qu.:142.0                      3rd Qu.:38.00                     
##  Max.   :201.0                      Max.   :83.00</code></pre>
<p>This function tries to give you some basic insight into the data, separately per column:</p>
<ul>
<li><code>SBP</code>:
<ul>
<li>The average is 131.5;</li>
<li>The median is close to the mean, and the 1st and 3rd quartile are at a similar distance from the mean. These are both indications that the values are distributed symmetrically around the mean;</li>
<li>The minimum is <em>much</em> closer to the mean than the maximum. This is an indication that the maximum value might be outlying.</li>
</ul></li>
<li><code>treatment</code>:
<ul>
<li>There are 90 observations;</li>
<li>This variable is treated as a <code>character</code> vector.</li>
</ul></li>
<li><code>age</code>:
<ul>
<li>The average is 35.7;</li>
<li>The median is close to the mean, and the 1st and 3rd quartile are at a similar distance from the mean. These are both indications that the values are distributed symmetrically around the mean;</li>
<li>The maximum is far away from the rest of the values, while the minimum is not. This could be an indication that the maximum value is outlying.</li>
</ul></li>
<li><code>sex</code>:
<ul>
<li>There are 90 observations;</li>
<li>This variable is treated as a <code>character</code> vector.</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="anova.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(DF)</span></code></pre></div>
<pre><code>##   SBP treatment age    sex
## 1 122  thiazide  32 female
## 2 119  thiazide  34 female
## 3 120  thiazide  36 female
## 4 129  thiazide  41   male
## 5 127  thiazide  35 female
## 6 118  thiazide  38 female</code></pre>
<p>This function simply shows the first 6 rows of the data. You can also print the last 6 with <code>tail</code> and change the number of rows printed by specifying <code>n</code>.</p>
</details>
<details>
<summary>
My output looks different
</summary>
<p>Then provided you did everything else correctly, the most likely reason is that your data was saved with a version of Excel where a comma is used as a decimal separator (e.g., the Dutch version). The solutions for this is simple, use <code>read.csv2</code>:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="anova.html#cb9-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;some-data-with-commas.csv&quot;</span>)</span></code></pre></div>
If that doesn’t work either, go over the details shown above, or watch the instructions in the <a href="https://youtu.be/BGUqZc-Pb8w">video</a>.
</details>
<details>
<summary>
Common mistakes
</summary>
<ul>
<li>Remember to include the file extension (e.g., “three-groups<strong>.csv</strong>”) when typing the file name.</li>
<li>You cannot read Excel files (.xls, .xlsx) with this function. Instead, follow the guide <a href="#read">here</a>, or save your data as CSV.</li>
<li>Don’t open the CSV file with Excel. You don’t need Excel or Google Sheets or any other program besides R and RStudio. If you have saved your data as CSV, you can close Excel.</li>
</ul>
</details>
<p>
<p>The next step is to ensure categorical variables are read as factors. This will allow us to use generic functions like <code>plot</code> and <code>summary</code> in a more meaningful way.</p>
<details>
<summary>
Why not just use <code>character</code>?
</summary>
<p>A character vector is just strings of text, numbers and/or symbols. If you were to produce a <code>summary</code>, this happens:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="anova.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DF<span class="sc">$</span>treatment)</span></code></pre></div>
<pre><code>##    Length     Class      Mode 
##        90 character character</code></pre>
<p>It tells us this object contains 60 values, and it is stored and treated as a string of text.</p>
<p>The generic <code>plot</code> function doesn’t even work at all:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="anova.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(SBP <span class="sc">~</span> treatment, DF)</span></code></pre></div>
<p><font color = "#C5060B"></p>
<pre><code>Error in plot.window(...) : need finite &#39;xlim&#39; values
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf</code></pre>
<p></font></p>
<p>Now convert the variables to factors and see how that changes the output. <br><small><em>(Run the code below, then run <code>summary(DF$treatment)</code>, or <code>plot(DF$treatment)</code> for example.)</em></small></p>
</details>
<p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="anova.html#cb14-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>treatment)</span>
<span id="cb14-2"><a href="anova.html#cb14-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>sex       <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>sex)</span></code></pre></div>
<div id="reordering-a-factor" class="section level3 unnumbered hasAnchor">
<h3>Reordering a Factor<a href="anova.html#reordering-a-factor" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>While it does not change any of the conclusions, it can help yourself and any readers if you put the groups in a logical order. For sex there is no logical order, but for treatment it would make sense to have the placebo first, as a reference to compare the other groups to.</p>
<p>To check the order of levels in a factor, use <code>levels</code>:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="anova.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(DF<span class="sc">$</span>treatment)</span></code></pre></div>
<pre><code>## [1] &quot;CCB&quot;      &quot;placebo&quot;  &quot;thiazide&quot;</code></pre>
<details>
<summary>
My output is <code>NULL</code>
</summary>
<p>That means you forgot to convert your variable to a factor first:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="anova.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(DF<span class="sc">$</span>treatment)</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="anova.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Solution</span></span>
<span id="cb19-2"><a href="anova.html#cb19-2" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>treatment)</span>
<span id="cb19-3"><a href="anova.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(DF<span class="sc">$</span>treatment)</span></code></pre></div>
<pre><code>## [1] &quot;CCB&quot;      &quot;placebo&quot;  &quot;thiazide&quot;</code></pre>
</details>
<p>
<p>To change which treatment appears first, use <code>relevel</code>:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="anova.html#cb21-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">relevel</span>(DF<span class="sc">$</span>treatment, <span class="st">&quot;placebo&quot;</span>)</span></code></pre></div>
<p><small><em>(Run <code>levels(DF$treatment)</code> again to see if it worked.)</em></small></p>
<details>
<summary>
Reordering multiple categories at once
</summary>
<p>If you want to change the order entirely, you can define the order manually as follows:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="anova.html#cb22-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>treatment, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;placebo&quot;</span>, <span class="st">&quot;CCB&quot;</span>, <span class="st">&quot;thiazide&quot;</span>))</span></code></pre></div>
</details>
<details>
<summary>
Change the names of the categories
</summary>
<p><font color = "orange"><i class = "fa fa-warning"></i></font> <small>Careful, only use this if you know what you are doing. Check the order of labels first, using <code>levels</code>. It is easy to accidentally flip the labels of a factor and end up with nonsense.</small></p>
<p>If you want to rename the labels of a factor, for instance because you think the names are too long, you can do so as follows:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="anova.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run this first, you have been warned</span></span>
<span id="cb23-2"><a href="anova.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(DF<span class="sc">$</span>treatment)</span>
<span id="cb23-3"><a href="anova.html#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="anova.html#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the names, taking into account the order of the labels above</span></span>
<span id="cb23-5"><a href="anova.html#cb23-5" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>treatment <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>treatment, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Ctrl&quot;</span>, <span class="st">&quot;CCB&quot;</span>, <span class="st">&quot;Thzd&quot;</span>))</span></code></pre></div>
<p><small><em>(Run <code>levels(DF$treatment)</code> again to see if it worked.)</em></small></p>
</details>
</div>
</div>
<div id="vis-ANOVA" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Visualize the Data<a href="anova.html#vis-ANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In summary:</p>
<ul>
<li><font color = "green"><i class = "fa fa-check"></i></font> Boxplots can be used as simple data exploration and to compare groups;</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> If you have <a href="reading-storing-data.html#tidy">multiple variables</a>, grouped boxplots can show combinations of groups;</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> A violin plot is an alternative to a boxplot.</li>
</ul>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="anova.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SBP <span class="sc">~</span> sex <span class="sc">+</span> treatment, DF)</span></code></pre></div>
<p><img src="Tutorials_files/figure-html/boxplot-ANOVA-1.png" width="672" /></p>
<details>
<summary>
What to look for
</summary>
<p><font size = 5><b>Potential Outliers</b></font></p>
<p>A boxplot shows either of the following:</p>
<div class="figure"><span style="display:block;" id="fig:IQR3"></span>
<img src="Tutorials_files/figure-html/IQR3-1.png" alt="What is displayed in a boxplot in case all observations are within a certain distance from the box (A), or otherwise (B)." width="672" />
<p class="caption">
Figure 3.1: What is displayed in a boxplot in case all observations are within a certain distance from the box (A), or otherwise (B).
</p>
</div>
<p>The interquartile range (IQR) is simply the size of the box. If all observations lie within <span class="math inline">\(1.5\times\)</span> this range from the box, then the whiskers show the extremes of the data (fig. <a href="#fig:IQR"><strong>??</strong></a> A). Otherwise, the observations are drawn separately <a href="#fig:IQR"><strong>??</strong></a> B). The IQR is usually not shown in a boxplot, but is used internally to calculate the location of the whiskers and marked observations (if any).</p>
<details>
<summary>
<font color = "orange"><i class = "fa fa-warning"></i></font> Marked observations are not outliers
</summary>
<p>This is a common misconception. Though it can be an <em>indication</em> of outlyingness, a boxplot alone <u>cannot</u> tell you whether these observations will strongly affect your analysis:</p>
<ul>
<li>If you have a large enough sample size, you <em>will</em> find more extreme observations, which are eventually drawn outside the IQR. Try running: <code>boxplot(rnorm(1000))</code></li>
<li>Skewed values (next section) will almost always show ‘outliers’ in the direction of skew, but these are unlikely to be outliers in the context of an appropriate model for skewed data.</li>
<li>The <span class="math inline">\(1.5\times\)</span> IQR rule is nothing special, it is merely convention. A boxplot is just a quick way to visualize numeric values.</li>
</ul>
</details>
<p>
<p><font size = 5><b>Skew</b></font></p>
<p>Skew means the data-generating process follows a probability distribution that is not symmetric. In a boxplot, skew looks like this:</p>
<div class="figure"><span style="display:block;" id="fig:skew3"></span>
<img src="Tutorials_files/figure-html/skew3-1.png" alt="A boxplot of symmetric (A), right-skewed (B), and left-skewed values." width="672" />
<p class="caption">
Figure 3.2: A boxplot of symmetric (A), right-skewed (B), and left-skewed values.
</p>
</div>
<p>Skew is not necessarily a problem, unless it persists in the residuals of a model that assumes normally distributed errors. For an explanation of skew, see the video on <a href="https://youtu.be/jdfG7rKPVNk">probability distributions <font color = "red"><i class="fa fa-youtube-play"></i></font></a>.</p>
<p><font size = 5><b>Differences Between Groups</b></font></p>
<p>A boxplot is not just a nice tool for <em>yourself</em> to inspect your data, but is also an effective tool to visually communicate the evidence for difference between groups:</p>
<div class="figure"><span style="display:block;" id="fig:boxplot-upgrade-ANOVA"></span>
<img src="Tutorials_files/figure-html/boxplot-upgrade-ANOVA-1.png" alt="A comparison of systolic blood pressure for different treatments and sex." width="384" />
<p class="caption">
Figure 3.3: A comparison of systolic blood pressure for different treatments and sex.
</p>
</div>
</details>
<details>
<summary>
How to improve your plot
</summary>
<p>Some basic adjustments that improve any plot:</p>
<ul>
<li>Use informative axis labels, with unit of measurement if appropriate;</li>
<li>Add an informative caption;</li>
<li>Keep the numbers on the axes horizontal where possible;</li>
<li>Remove unnecessary plot elements, like the box around the figure.</li>
</ul>
<p>The changes to the code I made below can all be found in the help pages <code>?boxplot</code> and <code>?par</code>. I am also a big fan of the <code>eaxis</code> function from the package <code>sfsmisc</code>. The caption is added as a chunk option (i.e., <code>```{r, fig.cap = "..."}</code>).</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="anova.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load a package for nice axes</span></span>
<span id="cb25-2"><a href="anova.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;sfsmisc&quot;</span>)</span>
<span id="cb25-3"><a href="anova.html#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the margins (bottom, left, top, right)</span></span>
<span id="cb25-4"><a href="anova.html#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">0</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fl">0.1</span>)</span>
<span id="cb25-5"><a href="anova.html#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="anova.html#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the locations (helps discern between combinations of groups)</span></span>
<span id="cb25-7"><a href="anova.html#cb25-7" aria-hidden="true" tabindex="-1"></a>where <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">7</span><span class="sc">:</span><span class="dv">8</span>)</span>
<span id="cb25-8"><a href="anova.html#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="anova.html#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the coordinate system</span></span>
<span id="cb25-10"><a href="anova.html#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SBP <span class="sc">~</span> sex <span class="sc">+</span> treatment, DF, <span class="at">at =</span> where, <span class="at">axes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb25-11"><a href="anova.html#cb25-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.5</span>, <span class="at">boxwex =</span> <span class="fl">0.25</span>, <span class="at">staplewex =</span> <span class="dv">0</span>, </span>
<span id="cb25-12"><a href="anova.html#cb25-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">110</span>, <span class="dv">200</span>), <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="dv">12</span>),</span>
<span id="cb25-13"><a href="anova.html#cb25-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Treatment&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Systolic blood pressure (mmHg)&quot;</span>)</span>
<span id="cb25-14"><a href="anova.html#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="anova.html#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add axes</span></span>
<span id="cb25-16"><a href="anova.html#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="fl">4.5</span>, <span class="fl">7.5</span>), <span class="fu">levels</span>(DF<span class="sc">$</span>treatment))</span>
<span id="cb25-17"><a href="anova.html#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">eaxis</span>(<span class="dv">2</span>)</span>
<span id="cb25-18"><a href="anova.html#cb25-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-19"><a href="anova.html#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a lightgrey background</span></span>
<span id="cb25-20"><a href="anova.html#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">9</span>, <span class="dv">9</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>, <span class="dv">210</span>, <span class="dv">210</span>, <span class="dv">100</span>), <span class="at">col =</span> <span class="st">&quot;grey95&quot;</span>,</span>
<span id="cb25-21"><a href="anova.html#cb25-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb25-22"><a href="anova.html#cb25-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="anova.html#cb25-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a simple grid</span></span>
<span id="cb25-24"><a href="anova.html#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">seq</span>(<span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">10</span>), <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> <span class="dv">1</span>)</span>
<span id="cb25-25"><a href="anova.html#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">seq</span>(<span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">20</span>), <span class="at">col =</span> <span class="st">&quot;white&quot;</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>)</span>
<span id="cb25-26"><a href="anova.html#cb25-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-27"><a href="anova.html#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Define two colors (picked from colorbrewer2.org):</span></span>
<span id="cb25-28"><a href="anova.html#cb25-28" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;#fb9a99&quot;</span>, <span class="st">&quot;#a6cee3&quot;</span>)</span>
<span id="cb25-29"><a href="anova.html#cb25-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-30"><a href="anova.html#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Redraw the boxplots on top</span></span>
<span id="cb25-31"><a href="anova.html#cb25-31" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(SBP <span class="sc">~</span> sex <span class="sc">+</span> treatment, DF, <span class="at">at =</span> where, <span class="at">axes =</span> <span class="cn">FALSE</span>,</span>
<span id="cb25-32"><a href="anova.html#cb25-32" aria-hidden="true" tabindex="-1"></a>        <span class="at">boxwex =</span> <span class="fl">0.25</span>, <span class="at">staplewex =</span> <span class="dv">0</span>, <span class="at">col =</span> cols, <span class="at">add =</span> <span class="cn">TRUE</span>, </span>
<span id="cb25-33"><a href="anova.html#cb25-33" aria-hidden="true" tabindex="-1"></a>        <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.5</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb25-34"><a href="anova.html#cb25-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-35"><a href="anova.html#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend</span></span>
<span id="cb25-36"><a href="anova.html#cb25-36" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topright&quot;</span>, <span class="at">legend =</span> <span class="fu">levels</span>(DF<span class="sc">$</span>sex), <span class="at">pch =</span> <span class="dv">15</span>, <span class="at">col =</span> cols, <span class="at">bty =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb25-37"><a href="anova.html#cb25-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-38"><a href="anova.html#cb25-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Restore the default margins for subsequent plots</span></span>
<span id="cb25-39"><a href="anova.html#cb25-39" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>) <span class="sc">+</span> <span class="fl">0.1</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-19"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-19-1.png" alt="A comparison of systolic blood pressure for three groups." width="384" />
<p class="caption">
Figure 3.4: A comparison of systolic blood pressure for three groups.
</p>
</div>
</details>
<p>
<p>From the plot you can conclude:</p>
<ul>
<li>There appears to be a clear outlier in the female CCB group;</li>
<li>None of the groups appear skewed;</li>
<li>Both the CCB and thiazide group have substantially lower blood pressure than the control, with thiazide appearing the lowest;</li>
<li>This difference appears to be similar for males and females;</li>
<li>Systolic blood pressure does not appear to differ by sex at all;</li>
<li>The variance of all groups is similar, because the boxes are similarly sized.</li>
</ul>
<p>This is just a sample, so whether this difference is <em>significant</em>, should be determined with a test.</p>
<details>
<summary>
Alternative: Violin plot
</summary>
<p>A more modern take on the boxplot is a <strong>violin plot</strong>. It combines a boxplot and a density plot. This type of visualization is richer in information than just a boxplot, but it is only meaningful if you have enough observations per group (e.g., &gt;10):</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="anova.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;vioplot&quot;</span>) <span class="co"># install if missing</span></span>
<span id="cb26-2"><a href="anova.html#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vioplot</span>(SBP <span class="sc">~</span> treatment, DF)</span></code></pre></div>
<p><img src="Tutorials_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<details>
<summary>
How to interpret a violin plot
</summary>
<p>Here is a breakdown of the components shown in a violin plot:</p>
<p><img src="Tutorials_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>The density plot, if you are unfamiliar with it, is like a continuous version of a histogram. It shows which values are more and less likely in the sample.</p>
</details>
</details>
<p>
</div>
<div id="analyze-the-data" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Analyze the Data<a href="anova.html#analyze-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<details>
<summary>
Summary (code)
</summary>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="anova.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages used (install if missing)</span></span>
<span id="cb27-2"><a href="anova.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb27-3"><a href="anova.html#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;emmeans&quot;</span>)</span>
<span id="cb27-4"><a href="anova.html#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="anova.html#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb27-6"><a href="anova.html#cb27-6" aria-hidden="true" tabindex="-1"></a>LM <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> treatment, DF)</span>
<span id="cb27-7"><a href="anova.html#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="anova.html#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform visual diagnostics</span></span>
<span id="cb27-9"><a href="anova.html#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))   <span class="co"># Plot in a 2x2 grid</span></span>
<span id="cb27-10"><a href="anova.html#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM, <span class="at">which =</span> <span class="dv">1</span>)    <span class="co"># Residuals vs fitted</span></span>
<span id="cb27-11"><a href="anova.html#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(LM, <span class="at">reps =</span> <span class="fl">1e4</span>) <span class="co"># QQ-plot</span></span>
<span id="cb27-12"><a href="anova.html#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM, <span class="at">which =</span> <span class="dv">3</span>)    <span class="co"># Scale-location</span></span>
<span id="cb27-13"><a href="anova.html#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM, <span class="at">which =</span> <span class="dv">4</span>)    <span class="co"># Cook&#39;s distance</span></span>
<span id="cb27-14"><a href="anova.html#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))   <span class="co"># Restore the default</span></span>
<span id="cb27-15"><a href="anova.html#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="anova.html#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Obs. 31 appears to be outlying:</span></span>
<span id="cb27-17"><a href="anova.html#cb27-17" aria-hidden="true" tabindex="-1"></a>DF[<span class="dv">31</span>, ]</span>
<span id="cb27-18"><a href="anova.html#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="anova.html#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Omitting this observation can be justified based on age</span></span>
<span id="cb27-20"><a href="anova.html#cb27-20" aria-hidden="true" tabindex="-1"></a>LM <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> treatment, DF[<span class="sc">-</span><span class="dv">31</span>, ])</span>
<span id="cb27-21"><a href="anova.html#cb27-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-22"><a href="anova.html#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform an omnibus test</span></span>
<span id="cb27-23"><a href="anova.html#cb27-23" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.aov</span>(LM)</span>
<span id="cb27-24"><a href="anova.html#cb27-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-25"><a href="anova.html#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="co"># If the omnibus test is significant, perform a post-hoc</span></span>
<span id="cb27-26"><a href="anova.html#cb27-26" aria-hidden="true" tabindex="-1"></a>EMM <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(LM, <span class="at">specs =</span> <span class="st">&quot;treatment&quot;</span>)</span>
<span id="cb27-27"><a href="anova.html#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(EMM)</span>
<span id="cb27-28"><a href="anova.html#cb27-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-29"><a href="anova.html#cb27-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Or treatment-vs-control style</span></span>
<span id="cb27-30"><a href="anova.html#cb27-30" aria-hidden="true" tabindex="-1"></a>EMM <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(LM, <span class="at">specs =</span> trt.vs.ctrl <span class="sc">~</span> treatment)</span>
<span id="cb27-31"><a href="anova.html#cb27-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-32"><a href="anova.html#cb27-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the post hoc (see the emmeans vignette)</span></span>
<span id="cb27-33"><a href="anova.html#cb27-33" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(EMM, <span class="at">comparisons =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
</details>
<p>
<div id="fit-the-model" class="section level3 unnumbered hasAnchor">
<h3>Fit the Model<a href="anova.html#fit-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the example, we are only interested in the effect of <code>treatment</code>. For a single grouping variable, use:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="anova.html#cb28-1" aria-hidden="true" tabindex="-1"></a>LM <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> treatment, DF)</span></code></pre></div>
<p>The general notation is <code>Outcome ~ GroupingVariable, Data</code>. Adding more grouping variables is simple, but model selection is not, so two-way and multi-way ANOVA are explained separately in the <a href="twowaymultiway.html#twowaymultiway">next chapter</a>.</p>
<details>
<summary>
Why use a linear model (<code>lm</code>)?
</summary>
<p><small><em>(The short answer is that ANOVA is linear and I decided to use <code>emmeans</code> throughout the tutorials for consistency.)</em></small></p>
<p>Linear means that we can express the model as intercept and slope(s):</p>
<p><span class="math display">\[\text{intercept} + \text{slope} \times \text{explanatory variable}\]</span></p>
<p>Categorical explanatory variables, like <code>treatment</code>, can be represented by <a href="https://youtu.be/3ZY9OSXmOrU?t=657">dummy variables <font color = "red"><i class="fa fa-youtube-play"></i></font></a>:</p>
<p><span class="math display">\[
\begin{aligned}
  x_1 &amp;=
    \begin{cases}
      1 \; \text{if CCB} \\
      0 \; \text{otherwise}
    \end{cases} \\ \\
  x_2 &amp;=
    \begin{cases}
      1 \; \text{if thiazide} \\
      0 \; \text{otherwise}
    \end{cases}
\end{aligned}
\]</span>
These variables are equal to <span class="math inline">\(1\)</span> if the observation belongs to that group and <span class="math inline">\(0\)</span> otherwise. Our example model then becomes:</p>
<p><span class="math display">\[\text{SBP} = \text{intercept} + \text{slope} \cdot x_1 + \text{slope} \cdot x_2 + \text{error}\]</span></p>
<p>That might look confusing at first, because this isn’t a slope in the everyday meaning of the word. But all that ‘slope’ means in statistics is the extent to which the outcome changes, if the explanatory variable increases by <span class="math inline">\(1\)</span>.</p>
<p>For example, if you belong to the thiazide group, then the equation becomes:</p>
<p><span class="math display">\[\text{SBP} = \text{intercept} + \text{slope} \cdot 0 + \text{slope} \cdot 1\]</span></p>
<p>If you belong to the control group, the equation becomes:</p>
<p><span class="math display">\[\text{SBP} = \text{intercept} + \text{slope} \cdot 0 + \text{slope} \cdot 0\]</span></p>
<p>Which is simply the value of the intercept.</p>
<p>Hence, comparing group means is the same as fitting a linear model with only dummy variables. This is useful for a number of reasons, but primarily:</p>
<ul>
<li>We can use the same notation for everything from <span class="math inline">\(t\)</span>-test to ANCOVA;</li>
<li>We can use <code>lm</code>, which is supported by far more functions than <code>aov</code>;</li>
<li>We can easily correct for <a href="https://youtu.be/RUX94txw4Qo">multiple testing <font color = "red"><i class="fa fa-youtube-play"></i></font></a>. <br><small><em>(The traditional <code>aov</code> + <code>TukeyHSD</code> approach does not correct for two-way or multi-way ANOVA.)</em></small></li>
</ul>
</details>
<p>
</div>
<div id="perform-diagnostics" class="section level3 unnumbered hasAnchor">
<h3>Perform Diagnostics<a href="anova.html#perform-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The calculation of confidence intervals and <span class="math inline">\(p\)</span>-values is based on several assumptions. If these are not reasonable, conclusions drawn from the analysis are invalid.</p>
<p>Additionally, outliers can have a strong influence on the estimates and <span class="math inline">\(p\)</span>-values, so you should always check and decide whether outlying observations are genuine, or outlying for reasons that warrant exclusion.</p>
<p>Checking assumptions and outlyingness can be done trough <a href="https://youtu.be/upJJmfSbBuQ">visual diagnostics <font color = "red"><i class="fa fa-youtube-play"></i></font></a>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="anova.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;car&quot;</span>)         <span class="co"># Install if missing</span></span>
<span id="cb29-2"><a href="anova.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))   <span class="co"># Plot in a 2x2 grid</span></span>
<span id="cb29-3"><a href="anova.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM, <span class="at">which =</span> <span class="dv">1</span>)    <span class="co"># Residuals vs fitted</span></span>
<span id="cb29-4"><a href="anova.html#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(LM, <span class="at">reps =</span> <span class="fl">1e4</span>) <span class="co"># QQ-plot</span></span>
<span id="cb29-5"><a href="anova.html#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM, <span class="at">which =</span> <span class="dv">3</span>)    <span class="co"># Scale-location</span></span>
<span id="cb29-6"><a href="anova.html#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM, <span class="at">which =</span> <span class="dv">4</span>)    <span class="co"># Cook&#39;s distance</span></span>
<span id="cb29-7"><a href="anova.html#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))   <span class="co"># Restore the default</span></span></code></pre></div>
<details>
<summary>
Show output
</summary>
<p><small><em>(For general advice on diagnostic plots, see the <a href="https://youtu.be/upJJmfSbBuQ">video <font color = "red"><i class="fa fa-youtube-play"></i></font></a>.)</em></small></p>
<p><img src="Tutorials_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>The visual diagnostics confirm what was already visible in the boxplots, there is an outlier (#31) visible in each of the plots. Its Cook’s distance is well over <span class="math inline">\(0.5\)</span>.</p>
<p>Let’s see what the diagnostics would look like without this observation:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="anova.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a model on the data, excluding obs. 31</span></span>
<span id="cb30-2"><a href="anova.html#cb30-2" aria-hidden="true" tabindex="-1"></a>LM2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> treatment, DF[<span class="sc">-</span><span class="dv">31</span>, ])</span>
<span id="cb30-3"><a href="anova.html#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="anova.html#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the diagnostics</span></span>
<span id="cb30-5"><a href="anova.html#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))    <span class="co"># Plot in a 2x2 grid</span></span>
<span id="cb30-6"><a href="anova.html#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM2, <span class="at">which =</span> <span class="dv">1</span>)    <span class="co"># Residuals vs fitted</span></span>
<span id="cb30-7"><a href="anova.html#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">qqPlot</span>(LM2, <span class="at">reps =</span> <span class="fl">1e4</span>) <span class="co"># QQ-plot</span></span>
<span id="cb30-8"><a href="anova.html#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM2, <span class="at">which =</span> <span class="dv">3</span>)    <span class="co"># Scale-location</span></span>
<span id="cb30-9"><a href="anova.html#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(LM2, <span class="at">which =</span> <span class="dv">4</span>)    <span class="co"># Cook&#39;s distance</span></span>
<span id="cb30-10"><a href="anova.html#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))    <span class="co"># Restore the default</span></span></code></pre></div>
<p><img src="Tutorials_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
Now the diagnostics look fine. If you are concerned about the staircase in the QQ-plot, that is an artifact of the way these data were collected: Systolic blood pressure was rounded to whole numbers, but the actual underlying values can reasonably be assumed to be approximately normally distributed within groups.
</details>
<details>
<summary>
What to look for in general
</summary>
<p><font size = 5><b>Deviations from Normality</b></font></p>
<p>In a QQ-plot, you can check whether the residuals deviate problematically from a normal distribution. The straight line represents a theoretical normal distribution and the black dots show where the actual residuals fall. Since the values a sample will <em>always</em> deviate somewhat, a confidence band is drawn around the line to provide an indication of the severity of the non-normality.</p>
<p><font color = "green"><i class="fa fa-check"></i></font> Here are three examples of random values drawn from an actual, exact normal distribution:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-28"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-28-1.png" alt="Normal QQ-plots of residuals from simulated data that follows a an exact normal distribution." width="672" />
<p class="caption">
Figure 3.5: Normal QQ-plots of residuals from simulated data that follows a an exact normal distribution.
</p>
</div>
<p>Note how even in data drawn from an <em>exact</em> normal distribution, occasional observations outside the confidence bands are quite common. This is important to keep in mind when judging the severity of a violation.</p>
<p>A great write-up (with examples) on what patterns to look for can be found in this <a href="https://stats.stackexchange.com/a/101290/176202">answer on CrossValidated <i class="fa fa-external-link"></i></a>. A quick summary of problematic patterns include:</p>
<ul>
<li>Gaps; <small><em>(Lack of values within a certain range.)</em></small></li>
<li>Bulging (concave or convex); <small><em>(Usually an indication of skew.)</em></small></li>
<li>S-shape; <small><em>(Implying light- or heavy-tailedness.)</em></small></li>
</ul>
<p><font color = "red"><i class="fa fa-times"></i></font> Here are three examples of problematic patterns: <font color = "grey">(confidence band hidden for clarity)</font></p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-29"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-29-1.png" alt="Normal QQ-plots of residuals displaying (A) gaps; (B) bulging; (C) S-shapedness ." width="672" />
<p class="caption">
Figure 3.6: Normal QQ-plots of residuals displaying (A) gaps; (B) bulging; (C) S-shapedness .
</p>
</div>
<p><font size = 5><b>Non-Constant Variance</b></font></p>
<p>In the <strong>residuals vs fitted</strong> plot, you can see whether the observations are more or less equally dispersed around their group means. The <span class="math inline">\(x\)</span>-axis shows the value of the group means and the <span class="math inline">\(y\)</span>-axis the deviation from the group mean.</p>
<p><font color = "green"><i class="fa fa-check"></i></font> Here are three examples of random values with equal group variance:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-30"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-30-1.png" alt="Residuals vs fitted plots of values drawn from a normal distribution with equal variance." width="672" />
<p class="caption">
Figure 3.7: Residuals vs fitted plots of values drawn from a normal distribution with equal variance.
</p>
</div>
<p>Important to note here is that small deviations will always be present, and a smoothing line will be drawn that is not useful for ANOVA (but will be used in linear regression).</p>
<p><small><em>(The smoothing line can be suppressed with <code>add.smooth = FALSE</code>.)</em></small></p>
<p><font color = "red"><i class="fa fa-times"></i></font> Examples of unequal variance in a residuals vs fitted plot:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-31"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-31-1.png" alt="Residuals vs fitted plots of values drawn from a normal distribution with unequal variance." width="672" />
<p class="caption">
Figure 3.8: Residuals vs fitted plots of values drawn from a normal distribution with unequal variance.
</p>
</div>
<p><font color = "orange"><i class="fa fa-warning"></i></font> Careful, unequal sample size can give the false appearance of unequal variance in a residuals vs fitted plot:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-32"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-32-1.png" alt="Residuals vs fitted plots of values drawn from a normal distribution with equal variance, but different sample sizes." width="672" />
<p class="caption">
Figure 3.9: Residuals vs fitted plots of values drawn from a normal distribution with equal variance, but different sample sizes.
</p>
</div>
<p><font color = "green"><i class="fa fa-check"></i></font> This is why you should also look at the <strong>scale-location</strong> plot:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-33"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-33-1.png" alt="Scale location plots of values drawn from a normal distribution with equal variance, but different sample sizes." width="672" />
<p class="caption">
Figure 3.10: Scale location plots of values drawn from a normal distribution with equal variance, but different sample sizes.
</p>
</div>
<p>The scale-location plot takes the residuals and performs a transformation that allows for a simple interpretation: Rather than looking at the <em>dispersion</em> in the black dots, you can look at the <em>average</em>. Higher variance means the red smoothing line is also higher.</p>
<p>As a rule of thumb, you should conclude non-constant variance from a scale-location plot if the smoothing line is more than <span class="math inline">\(0.5\)</span> higher/lower than other groups, or there is a consistent trend up/down.</p>
<p><font color = "red"><i class="fa fa-times"></i></font> Examples of non-constant variance in a scale-location plot:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-34"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-34-1.png" alt="Scale-location plots of values drawn from a normal distribution with unequal variance." width="672" />
<p class="caption">
Figure 3.11: Scale-location plots of values drawn from a normal distribution with unequal variance.
</p>
</div>
<p><font size = 5><b>Potential Outliers</b></font></p>
<p>The Cook’s distance can be used to assess outlyingness. This is a simple measure: Greater than <span class="math inline">\(0.5\)</span> warrants further inspection and greater than <span class="math inline">\(1.0\)</span> is statistically outlying.</p>
<p><font color = "green"><i class="fa fa-check"></i></font> Here are three examples of random normally distributed values without any apparent outliers:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-35"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-35-1.png" alt="Cook's distance of values drawn from a normal distribution." width="672" />
<p class="caption">
Figure 3.12: Cook’s distance of values drawn from a normal distribution.
</p>
</div>
<p><font color = "red"><i class="fa fa-times"></i></font> Here are three examples of outliers:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-36"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-36-1.png" alt="Cook's distance of values drawn from a $t$-distribution. Due to the larger mass in the tails, the $t$-distribution is more likely to yield outlying values." width="672" />
<p class="caption">
Figure 3.13: Cook’s distance of values drawn from a <span class="math inline">\(t\)</span>-distribution. Due to the larger mass in the tails, the <span class="math inline">\(t\)</span>-distribution is more likely to yield outlying values.
</p>
</div>
</details>
<details>
<summary>
Why <span class="math inline">\(t\)</span>-quantiles instead of normal?
</summary>
<p><small><em>(This is a bit technical and only important if, for example, a reviewer asks about it.)</em></small></p>
<p>In short, I recommend using this over a normal QQ-plot, because it reflects the general notion that minor deviations in the tails should be ignored.</p>
<p>You may have noticed that the example code here does not actually produce a normal QQ-plot, but instead a QQ-plot for a theoretical <span class="math inline">\(t\)</span>-distribution. <small><em>(Try: <code>qqPlot(lm(rnorm(10) ~ 1))</code> and look at the <span class="math inline">\(x\)</span>-axis label.)</em></small></p>
<p>A little digging in the <code>qqPlot</code>’s <a href="https://github.com/cran/car/blob/master/R/qqPlot.R#L233">github repository <i class = "fa fa-external-link"></i></a> shows what happens:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="anova.html#cb31-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="cf">if</span> (distribution <span class="sc">==</span> <span class="st">&#39;t&#39;</span>) <span class="fu">qt</span>(P, <span class="at">df=</span>res.df<span class="dv">-1</span>) <span class="cf">else</span> <span class="fu">qnorm</span>(P)</span></code></pre></div>
<p><small><em>(Here, <code>z</code> is the theoretical quantile on the <span class="math inline">\(x\)</span>-axis of a QQ-plot.)</em></small></p>
<p>These quantiles are used to compute where the confidence band should be drawn. If you use <code>qqPlot(LM)</code>, these are based on a <span class="math inline">\(t\)</span>-distribution with degrees of freedom equal to the residual degrees of freedom of the model minus one. This is done to reflect the additional uncertainty from the limited sample size. As the sample size grows (and the model complexity remains constant), the two approaches grow closer. In practical terms, this allows for slightly wider bands near the tails, the smaller the sample size is, which is a desirable property, because the smaller the sample size, the harder it is to decide whether an observation is outlying.</p>
<p>Another important difference you may have noticed is that <code>qqPlot(LM)</code> yields a narrower confidence band than <code>qqPlot(residuals(LM))</code>. This actually has nothing to do with the <span class="math inline">\(t\)</span>-distribution, but with the type of confidence band drawn when using <code>qqPlot(LM)</code>: The default argument for <code>qqPlot(residuals(LM))</code> is <code>line = "quartiles"</code>, whereas <code>qqPlot(LM)</code> defaults to <code>line = "robust"</code>. The latter provides simulation-based robust regression confidence bands, which are more sensitive to non-normality, while simultaneously being less prone to false positives.<span class="citation"><sup><a href="#ref-car" role="doc-biblioref">1</a></sup></span></p>
<p>On a general note, these bands are (both) point-based 95% confidence, meaning that there is a large chance of at least one observation outside the bands, even if the values come from a theoretical normal distribution.</p>
</details>
<details>
<summary>
Significance tests for assumptions
</summary>
<p><font color = "orange"><i class = "fa fa-warning"></i></font> <small>All significance tests can produce false positives. Always judge the severity of any supposed problems with <em>visual</em> diagnostics.</small></p>
<p>In cases where you are not sure an assumption is violated, it is possible to conduct a test.</p>
<p><font size = 5><b>Normality</b></font></p>
<p>Deviations from conditional normality can be formally tested using a variety of tests, all of which have different sensitivities to different aspects of the normal probability distribution. Commonly used is the Shapiro–Wilks test, which is particularly sensitive to skew and light-tailedness.<span class="citation"><sup><a href="#ref-ShapiroSensitivities" role="doc-biblioref">2</a></sup></span></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="anova.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(LM))</span></code></pre></div>
<details>
<summary>
Show output
</summary>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(LM)
## W = 0.48457, p-value = 3.255e-16</code></pre>
<p>The residuals differ significantly from a theoretical normal distribution (<span class="math inline">\(p = 3.23 \cdot 10^{-16}\)</span>), though this is likely due to the outlier seen in the visual diagnostics, which is something you can try out:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="anova.html#cb34-1" aria-hidden="true" tabindex="-1"></a>LM2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> treatment, DF[<span class="sc">-</span><span class="dv">31</span>, ])</span>
<span id="cb34-2"><a href="anova.html#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">residuals</span>(LM2))</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  residuals(LM2)
## W = 0.97918, p-value = 0.1634</code></pre>
<p>And indeed, now there is no detected deviation from normality anymore.</p>
<details>
<summary>
<font color = "orange"><i class = "fa fa-warning"></i></font> This does not demonstrate the values are normally distributed
</summary>
<p>This is a common misconception. All we found is a lack of evidence against normality. But for these values to be normally distributed, they would need to range all the way from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>, which is obviously not realistic for blood pressure.</p>
<small><em>Also see: <a href="https://stats.stackexchange.com/a/85914/176202">Why do statisticians say a non-significant result means “you can’t reject the null” as opposed to accepting the null hypothesis?</a></em></small>
</details>
</details>
<p>
<p><font size = 5><b>Constant Variance</b></font></p>
<p>A robust test for non-constant variance that is not sensitive to other common issues like outliers and non-normality is the Breusch–Pagan test:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="anova.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;lmtest&quot;</span>) <span class="co"># Install if missing</span></span>
<span id="cb36-2"><a href="anova.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(LM)</span></code></pre></div>
<details>
<summary>
Show output
</summary>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  LM
## BP = 2.2161, df = 2, p-value = 0.3302</code></pre>
<p>As expected from the visual diagnostics, group variances are not significantly different (<span class="math inline">\(p = 0.330\)</span>).</p>
<details>
<summary>
<font color = "orange"><i class = "fa fa-warning"></i></font> This does not demonstrate the groups have equal variance
</summary>
<p>This is a common misconception. All we found is a lack of evidence <em>against</em> equal variance.</p>
<small><em>Also see: <a href="https://stats.stackexchange.com/a/85914/176202">Why do statisticians say a non-significant result means “you can’t reject the null” as opposed to accepting the null hypothesis?</a></em></small>
</details>
</details>
<p>
<p><font size = 5><b>Outliers</b></font></p>
<p>A test for outlyingness is included in the <code>car</code> package:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="anova.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb38-2"><a href="anova.html#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">outlierTest</span>(LM)</span></code></pre></div>
<details>
<summary>
Show output
</summary>
<pre><code>##    rstudent unadjusted p-value Bonferroni p
## 31 18.55085         8.3005e-32   7.4705e-30</code></pre>
<p>The test looks at every individual residual and whether it might be outlying. That of course, poses a major multiple testing issue, so the resulting <span class="math inline">\(p\)</span>-values are adjusted for this. When looking for outliyngness, always check the <em>adjusted</em> <span class="math inline">\(p\)</span>-value.</p>
<p>In this case, the test is significant (<span class="math inline">\(p_{\text{adj}} = 7.47 \cdot 10^{-30}\)</span>) and observation 31 is again pointed out to be the offending observation.</p>
</details>
<p>The <code>car</code> package contains another set of residual plots specifically to assess outlyingness:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="anova.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">influenceIndexPlot</span>(LM)</span></code></pre></div>
<details>
<summary>
Show output
</summary>
<p><img src="Tutorials_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<p>These show, in order:</p>
<ul>
<li>The Cook’s distance; <small><em>(Greater than <span class="math inline">\(0.5\)</span> is noteworthy, greater than <span class="math inline">\(1.0\)</span> is outlying.)</em></small></li>
<li>The studentized residuals; <small><em>(Divided by their standard deviation for standardized interpretation.)</em></small></li>
<li><span class="math inline">\(P\)</span>-values for outlyingess; <small><em>(Corrected for <a href="https://youtu.be/RUX94txw4Qo">multiple testing</a>.)</em></small></li>
<li>The hat-values. <small><em>(A measure of relative influence.)</em></small></li>
</ul>
<p>Observation 31 is again pointed out.</p>
</details>
</details>
<details>
<summary>
What to do if an assumption is violated?
</summary>
<p>Below are some options, in the order I would consider them:</p>
<ul>
<li>Using a model that makes different distributional assumptions (e.g., GLM, GAM);</li>
<li>Finding an appropriate transformation of the outcome that can also be justified from a biological point of view;</li>
<li>Using robust linear regression to account for non-constant variance, or give less weight to outliyng observations (e.g., with <code>rlm</code> from the <code>MASS</code> package);</li>
<li>Using a test that makes no distributional assumptions. <small><em>(For example, the Kruskal–Wallis test (<code>kruskal.test</code>), followed by pairwise Wilcoxon tests (<code>wilcox.test</code>) for individual differences, with an appropriate multiple testing correction applied (<code>p.adjust</code>).)</em></small></li>
</ul>
</details>
<p>
</div>
<div id="outlierexample" class="section level3 unnumbered hasAnchor">
<h3>Dealing with Potential Outliers<a href="anova.html#outlierexample" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In general, outliers should <strong>not</strong> be removed from the data, barring some exceptions.</p>
<p><font color = "green"><i class = "fa fa-check"></i></font> The following are valid reasons for exclusion:</p>
<ol style="list-style-type: decimal">
<li>The observation is clearly an unrealistic value; <br><small><em>(For example, a blood pressure of “2000 mmHg” due to a misplaced decimal separator.)</em></small></li>
<li>The cause of outlyingness can be traced back, invalidating the observation; <br><small><em>(For example, because the blood pressure monitor was placed incorrectly.)</em></small></li>
<li>The observation differs in another way from the rest, invalidating comparisons. <br><small><em>(For example, this person smoked and all others did not.)</em></small></li>
</ol>
<p><font color = "red"><i class = "fa fa-times"></i></font> The following are insufficient reasons for exclusion:</p>
<ul>
<li>The observation stands out in the diagnostic plots;</li>
<li>The observation has a high Cook’s distance;</li>
<li>An outlier test showed the value was significantly outlying.</li>
</ul>
<p>These are all measures that assume your model is right, but the opposite could very well be the case: The fact that there <em>are</em> ‘outliers’ is often an indication the proposed model is wrong.</p>
<p>Which is the case in our example? Let’s inspect observation 31 once again:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="anova.html#cb41-1" aria-hidden="true" tabindex="-1"></a>DF[<span class="dv">31</span>, ]</span></code></pre></div>
<pre><code>##    SBP treatment age    sex
## 31 201       CCB  83 female</code></pre>
<p>The observation belongs to an 83-year old individual, which is considerably older than any of the other participants. If there had been more elderly individuals, we could opt to include <code>age</code> in the model. In this case though, there is only one observation this much older than the rest <em>and</em> it happens to have an outlying value for blood pressure, making this fall into category 3, warranting exclusion.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="anova.html#cb43-1" aria-hidden="true" tabindex="-1"></a>DF2 <span class="ot">&lt;-</span> DF[<span class="sc">-</span><span class="dv">31</span>, ]</span>
<span id="cb43-2"><a href="anova.html#cb43-2" aria-hidden="true" tabindex="-1"></a>LM <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> treatment, DF2)</span></code></pre></div>
<p><font color = "orange"><i class = "fa fa-warning"></i></font> <small>This is a new model, fitted to different data, so you should rerun the diagnostics.</small></p>
<details>
<summary>
I can’t trace back the source of outlyingness
</summary>
<p>Then you have two options:</p>
<ul>
<li>Compare the results with and without the suspected outlier. If you end up with similar numbers and arrive more or less at the same conclusion, you could opt to simply mention the outlier (and its influence) in the results and write your conclusion normally; <br><small><em>(Even better would be to include both outputs (e.g., as supplementary.)</em></small></li>
<li>Use an alternative to ANOVA, like the Kruskal–Wallis test, which does not make the same distributional assumptions. <br><small><em>(See <code>?kruskal.test</code>.)</em></small></li>
</ul>
</details>
<details>
<summary>
My data set has many outliers
</summary>
<p>This is more often than not an indication that the assumptions of the model are not reasonable in the first place: Perhaps the data-generating process produced skewed values, or has far heavier tails than the normal distribution does. Perhaps there is an error in how the data are collected, or maybe your data were not read correctly by the software.</p>
<p>Simple removal is at best a questionable research practice and at worst plain falsification. Unless you can trace back the origin of the outliers, consider consulting a statistician.</p>
</details>
<p>
</div>
<div id="perform-an-omnibus-test" class="section level3 unnumbered hasAnchor">
<h3>Perform an Omnibus Test<a href="anova.html#perform-an-omnibus-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To print a classic ANOVA table, run the following:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="anova.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary.aov</span>(LM)</span></code></pre></div>
<details>
<summary>
Show output
</summary>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## treatment    2   8921    4460   283.6 &lt;2e-16 ***
## Residuals   86   1353      16                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The omnibus test is significant (<span class="math inline">\(F = 283.6\)</span>, <span class="math inline">\(p &lt; 2 \cdot 10^{-16}\)</span>), meaning there is a significant difference among group means. For a full explanation of the table above, see the <a href="https://youtu.be/87ECInQIY9k?t=129">video <font color = "red"><i class="fa fa-youtube-play"></i></font></a>.</p>
</details>
<p>
</div>
<div id="perform-a-post-hoc-analysis" class="section level3 unnumbered hasAnchor">
<h3>Perform a Post Hoc Analysis<a href="anova.html#perform-a-post-hoc-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><font color = "orange"><i class = "fa fa-warning"></i></font> <small>If the omnibus test is not significant, skip this section.</small></p>
<p>After concluding that there is a difference among means, a post hoc can be used to compare individual groups and determine <em>which</em> groups differ. If you simply want to compare all groups with all other groups, you can do so like this:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="anova.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;emmeans&quot;</span>)</span>
<span id="cb46-2"><a href="anova.html#cb46-2" aria-hidden="true" tabindex="-1"></a>EMM <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(LM, <span class="at">specs =</span> <span class="st">&quot;treatment&quot;</span>)</span>
<span id="cb46-3"><a href="anova.html#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(EMM)</span></code></pre></div>
<details>
<summary>
Show output
</summary>
<pre><code>##  contrast           estimate   SE df t.ratio p.value
##  placebo - CCB         18.33 1.03 86  17.746  &lt;.0001
##  placebo - thiazide    23.13 1.02 86  22.592  &lt;.0001
##  CCB - thiazide         4.81 1.03 86   4.653  &lt;.0001
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>All groups differ significantly from each other (<span class="math inline">\(p &lt; 0.0001\)</span>), with thiazide appearing most effective. These <span class="math inline">\(p\)</span>-values are already corrected for multiple testing.</p>
<p>If you want to obtain the actual, non-discretized <span class="math inline">\(p\)</span>-values, you can use <code>as.data.frame</code>:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="anova.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(<span class="fu">pairs</span>(EMM))</span></code></pre></div>
<pre><code>##             contrast  estimate       SE df   t.ratio      p.value
## 1      placebo - CCB 18.327586 1.032768 86 17.746090 2.591527e-10
## 2 placebo - thiazide 23.133333 1.023978 86 22.591634 2.591527e-10
## 3     CCB - thiazide  4.805747 1.032768 86  4.653271 3.476791e-05</code></pre>
</details>
<p>
<p>Since this incurs a <a href="https://youtu.be/RUX94txw4Qo">multiple testing</a> problem, it is good practice to limit the comparisons to only those strictly necessary to answer the research question.</p>
<details>
<summary>
Treatment-vs-control style comparison
</summary>
<p>In the example used so far, we could have chosen to only compare the treatments to the control group (and not to each other). The package <code>emmeans</code> has a built-in argument to support this option:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="anova.html#cb50-1" aria-hidden="true" tabindex="-1"></a>EMM <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(LM, <span class="at">specs =</span> trt.vs.ctrl <span class="sc">~</span> treatment)</span>
<span id="cb50-2"><a href="anova.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(EMM<span class="sc">$</span>contrasts) <span class="co"># as.data.frame prevents rounding</span></span></code></pre></div>
<details>
<summary>
Show output
</summary>
<pre><code>##             contrast  estimate       SE df   t.ratio      p.value
## 1      CCB - placebo -18.32759 1.032768 86 -17.74609 1.295763e-10
## 2 thiazide - placebo -23.13333 1.023978 86 -22.59163 1.295763e-10</code></pre>
Note how the <span class="math inline">\(p\)</span>-values are now lower than when we compared all-vs-all. This is because the multiple testing correction only corrects for two tests.
</details>
</details>
<details>
<summary>
Custom comparisons
</summary>
<p><font color = "orange"><i class = "fa fa-warning"></i></font> <small>Only use this if you have <em>a priori</em> reasons to exclude certain comparisons. You cannot first perform all comparisons and then decide which comparisons to keep. This is a form of <a href="https://en.wikipedia.org/wiki/Data_dredging"><span class="math inline">\(p\)</span>-hacking</a>.</small></p>
<p>If your research question can be answered satisfactorily with a specific set of comparisons, you can do so by creating custom contrasts. This is beyond the scope of this tutorial, but well documented in the <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/comparisons.html#linfcns"><code>emmeans</code> vignette <i class = "fa fa-external-link"></i></a>.</p>
</details>
<details>
<summary>
Obtaining confidence intervals for group means
</summary>
<p>Comparisons show you the estimated <em>differences</em>. But what if you wanted to include confidence intervals for the estimated <em>group means</em> (a common request by reviewers)? You can obtain those by printing the object we just created:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="anova.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(EMM) <span class="co"># as.data.frame prevents rounding</span></span></code></pre></div>
<pre><code>##   treatment   emmean        SE df lower.CL upper.CL
## 1   placebo 144.5000 0.7240617 86 143.0606 145.9394
## 2       CCB 126.1724 0.7364397 86 124.7084 127.6364
## 3  thiazide 121.3667 0.7240617 86 119.9273 122.8061</code></pre>
<p>The confidence intervals are:</p>
<ul>
<li>Placebo: 143.1–145.9</li>
<li>CCB: 124.7–127.6</li>
<li>Thiazide: 119.9–122.8</li>
</ul>
<p>It is also possible to plot the confidence intervals:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="anova.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(EMM, <span class="at">xlab =</span> <span class="st">&quot;Systolic blood pressure (mmHg)&quot;</span>)</span></code></pre></div>
<p><img src="Tutorials_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
</details>
</div>
</div>
<div id="results-ANOVA" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Correctly Phrase the Results<a href="anova.html#results-ANOVA" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<details>
<summary>
If the <span class="math inline">\(p\)</span>-value of the omnibus test is <strong>less</strong> than the chosen level of significance
</summary>
<p><Small><em>(This is the case in the example.)</em></small></p>
<p>While you can technically still summarize three comparisons in writing, it is right at the border of what should be put in a table instead, and referred to in brief. Generally, for post hoc analyses I recommend showing the average differences, confidence intervals and <span class="math inline">\(p\)</span>-values in a table and/or figure. However, this section is meant to help you <em>phrase</em> results, so examples are provided regardless.</p>
<p>Examples of precise language:</p>
<ul>
<li><font color = "green"><i class = "fa fa-check"></i></font> Systolic blood pressure differed significantly by type of treatment (<span class="math inline">\(p &lt; 2 \cdot 10^{-16}\)</span>), with CCB and thiazide resulting in 18.3 and 23.1 mmHg lower blood pressure on average, respectively (CCB: <span class="math inline">\(p = 2.59 \cdot 10^{-10}\)</span>, thiazide: <span class="math inline">\(p = 2.59 \cdot 10^{-10}\)</span>);</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> The thiazide group had significantly lower systolic blood pressure than CCB (<span class="math inline">\(\hat{\beta} = 4.8\)</span> mmHg, <span class="math inline">\(p = 3.48 \cdot 10^{-5}\)</span>);</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> Thiazide resulted in 4.8 mmHg lower systolic blood pressure on average (95% CI: 2.3–7.3).</li>
</ul>
<p>Examples of incorrect, incomplete, or imprecise language:</p>
<ul>
<li><font color = "red"><i class = "fa fa-times"></i></font> The alternative hypothesis was true // The null-hypothesis was false;</li>
<li><font color = "red"><i class = "fa fa-times"></i></font> The difference was significant (<span class="math inline">\(p &lt; 0.05\)</span>);</li>
<li><font color = "red"><i class = "fa fa-times"></i></font> The treatments outperform the control.</li>
</ul>
<details>
<summary>
Why paste tense?
</summary>
<p>The results of a single experiment, no matter how convincing, can never prove something to be true. The results <em>were</em> observed, and in this one experiment, the treatments outperformed the control.</p>
<p>Use present tense only for statements that have been demonstrated repeatedly, are generally agreed upon, or are easily observable, e.g.:</p>
<ul>
<li>Smoking causes cancer;</li>
<li>Current climate-change is mainly caused by human activities;</li>
<li>Most people use smartphones nowadays.</li>
</ul>
</details>
</details>
<details>
<summary>
If the <span class="math inline">\(p\)</span>-values of the omnibus test is <strong>greater</strong> than the chosen level of significance
</summary>
<p>Examples of precise language:</p>
<ul>
<li><font color = "green"><i class = "fa fa-check"></i></font> Systolic blood pressure did not differ significantly by type of treatment (<span class="math inline">\(p = \dots\)</span>);</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> There is insufficient evidence to conclude either treatment worked (<span class="math inline">\(p = \dots\)</span>);</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> There was a trend towards lower blood pressure on either treatment, but the differences were not significant (<span class="math inline">\(p = \dots\)</span>).</li>
</ul>
<p>Examples of incorrect, incomplete, or imprecise language:</p>
<ul>
<li><font color = "red"><i class = "fa fa-times"></i></font> The treatments did not work;</li>
<li><font color = "red"><i class = "fa fa-times"></i></font> There was no difference (<span class="math inline">\(p &lt; 0.05\)</span>);</li>
<li><font color = "red"><i class = "fa fa-times"></i></font> We accept the null-hypothesis.</li>
</ul>
<details>
<summary>
Why can’t I say I <em>accepted</em> the null-hypothesis?
</summary>
<p>This is imprecise language because it distorts the order of null-hypothesis significance testing. Every tests <em>starts</em> with pretending the null-hypothesis is true, and then considering how rare a result this would be. You did not accept the null-hypothesis <em>because</em> of the <span class="math inline">\(p\)</span>-value, but rather, you started by taking on the null-hypothesis to even compute that <span class="math inline">\(p\)</span>-value.</p>
<p><small>Also see: <a href="https://stats.stackexchange.com/a/85914/176202">Why do statisticians say a non-significant result means “you can’t reject the null” as opposed to accepting the null hypothesis?</a></small></p>
</details>
<p>
<p>If the omnibus test was insignificant, this is where the analysis ends. Do not include a post hoc, as that could be considered a form of <a href="https://en.wikipedia.org/wiki/Data_dredging">fishing</a>.</p>
</details>
</div>
<div id="incorporating-this-in-a-paper-2" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Incorporating This in a Paper<a href="anova.html#incorporating-this-in-a-paper-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here you can find examples of how to justify the methods used, explain the results found and write a discussion. This is meant to show you what belongs where, and what level of detail is common in scientific literature.</p>
<p>Remember to use your own words—<strong>paraphrase to avoid plagiarism</strong>.</p>
<details>
<summary>
Methods
</summary>
<p><small><em>(In this section, you should describe the data collection and analysis to an extent that a fellow expert could reproduce your study.)</em></small></p>
<p>A total of <span class="math inline">\(n = 90\)</span> Dutch individuals with clinically diagnosed hypertension were selected for the study. Inclusion criteria included: Minimum blood pressure of 140/90 mmHg, or an average of 135/85 mmHg at home; Primary hypertension; No evidence of other disease within 1 month of starting treatment. Written informed consent was obtained from all individuals and this study was approved by the ethical committee of Example institute under approval number 123456789. Individuals were randomly assigned to either a calcium channel blocker (CCB), thiazide, or an appropriate placebo. A summary of patient characteristics is provided in table ….</p>
<p>Statistical analyses were conducted in R, version 4.2.1, using the RStudio interface.<span class="citation"><sup><a href="#ref-R" role="doc-biblioref">3</a>,<a href="#ref-RStudio" role="doc-biblioref">4</a></sup></span> Differences in group means were assessed with a one-way ANOVA. A post hoc was conducted with the <code>emmeans</code> package, using the Tukey method to adjust for multiple testing.<span class="citation"><sup><a href="#ref-emmeans" role="doc-biblioref">5</a></sup></span> Approximate conditional normality was assessed through normal quantile-quantile plots, using the <code>car</code> package,<span class="citation"><sup><a href="#ref-car" role="doc-biblioref">1</a></sup></span> and constant variance with a scale-location plot.</p>
<p>Note:</p>
<ul>
<li>Check your R version number with <code>version</code>;</li>
<li>Justify the model used; <small><em>(Are the assumptions of ANOVA reasonable; What did you do to assess this?)</em></small></li>
<li>You should cite any packages used to perform analyses, generate tables or figures that made it into the paper, e.g.;
<ul>
<li><font color = "green"><i class = "fa fa-check"></i></font> Normal quantile-quantile plots were generated with the <code>car</code> package.<span class="citation"><sup><a href="#ref-car" role="doc-biblioref">1</a></sup></span></li>
</ul></li>
<li>You should <em>not</em> cite packages used only internally, e.g.:
<ul>
<li><font color = "red"><i class = "fa fa-times"></i></font> We used <code>readxl</code> to enter the data in R.<span class="citation"><sup><a href="#ref-readxl" role="doc-biblioref">6</a></sup></span></li>
</ul></li>
</ul>
</details>
<details>
<summary>
Results
</summary>
<p><small><em>(In this section you should mention the results without giving any interpretation yet.)</em></small></p>
<p>For general advice on phrasing, see: <a href="anova.html#results-ANOVA">Correctly Phrase the Results</a>. In this section, you should include your boxplot and explain in brief what the outcome of the ANOVA and (if applicable) post hoc was. For example:</p>
<blockquote>
<p>Systolic blood pressure differed significantly between treatment groups (<span class="math inline">\(F = 283.6\)</span>, <span class="math inline">\(p &lt; 2 \cdot 10^{-16}\)</span>), with both treatments resulting in significantly lower systolic blood pressure (table <a href="anova.html#tab:tab-ANOVA">3.1</a>). Diagnostic plots revealed no problematic deviations from normality and constant variance (Supplementary Figure <strong>S…</strong>). A single outlying value for systolic blood pressure was omitted from the analysis due to the individual’s age far exceeding that of all other participants. Excluding this observation did not affect which null-hypotheses were rejected.</p>
</blockquote>
<p>It is very common to see boxplots with significance stars, but the interpretation of these stars is not consistent and you should mention the actual, non-discretized <span class="math inline">\(p\)</span>-value at least somewhere in the results.</p>
<p>The post hoc can be presented as follows: <small><em>(In the example, treatment-vs-control style.)</em></small></p>
<table>
<caption>
<span id="tab:tab-ANOVA">Table 3.1: </span>Post hoc comparison with Tukey correction for multiple testing.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Comparison
</th>
<th style="text-align:left;">
Estimate
</th>
<th style="text-align:left;">
SE
</th>
<th style="text-align:left;">
df
</th>
<th style="text-align:left;">
<span class="math inline">\(t\)</span>-value
</th>
<th style="text-align:left;">
<span class="math inline">\(p\)</span>-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
CCB - placebo
</td>
<td style="text-align:left;">
<span class="math inline">\(-18.33\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1.03\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(86\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-17.75\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1.30 \cdot 10^{-10}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
thiazide - placebo
</td>
<td style="text-align:left;">
<span class="math inline">\(-23.13\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1.02\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(86\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-22.59\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(1.30 \cdot 10^{-10}\)</span>
</td>
</tr>
</tbody>
</table>
<details>
<summary>
How do you create a table like that in R?
</summary>
<p><font color = "darkgreen"><i class = "fa fa-thumbs-up"></i></font> By going through the pain of learning <a href="https://en.wikipedia.org/wiki/Regular_expression">regular expressions</a>.</p>
<p>Here is the code I used:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="anova.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(<span class="st">&quot;knitr&quot;</span>)</span>
<span id="cb55-2"><a href="anova.html#cb55-2" aria-hidden="true" tabindex="-1"></a>digits <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb55-3"><a href="anova.html#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="anova.html#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Take the output you want to create a table of</span></span>
<span id="cb55-5"><a href="anova.html#cb55-5" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(EMM<span class="sc">$</span>contrasts) </span>
<span id="cb55-6"><a href="anova.html#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="anova.html#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add some column names</span></span>
<span id="cb55-8"><a href="anova.html#cb55-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(M) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Comparison&quot;</span>, <span class="st">&quot;Estimate&quot;</span>, <span class="st">&quot;SE&quot;</span>, <span class="st">&quot;df&quot;</span>, <span class="st">&quot;$t$-value&quot;</span>, <span class="st">&quot;$p$-value&quot;</span>)</span>
<span id="cb55-9"><a href="anova.html#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="anova.html#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Take all numeric values</span></span>
<span id="cb55-11"><a href="anova.html#cb55-11" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">unlist</span>(M[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb55-12"><a href="anova.html#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="anova.html#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert them to...</span></span>
<span id="cb55-14"><a href="anova.html#cb55-14" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb55-15"><a href="anova.html#cb55-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ...scientific notation if less than 0.01</span></span>
<span id="cb55-16"><a href="anova.html#cb55-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abs</span>(x) <span class="sc">&lt;</span> <span class="fl">0.01</span>, </span>
<span id="cb55-17"><a href="anova.html#cb55-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">formatC</span>(x, <span class="at">format =</span> <span class="st">&quot;e&quot;</span>, <span class="at">digits =</span> digits),</span>
<span id="cb55-18"><a href="anova.html#cb55-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(</span>
<span id="cb55-19"><a href="anova.html#cb55-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ...integer if equal to its rounded value</span></span>
<span id="cb55-20"><a href="anova.html#cb55-20" aria-hidden="true" tabindex="-1"></a>    x <span class="sc">==</span> <span class="fu">round</span>(x),</span>
<span id="cb55-21"><a href="anova.html#cb55-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">formatC</span>(x, <span class="at">format =</span> <span class="st">&quot;d&quot;</span>),</span>
<span id="cb55-22"><a href="anova.html#cb55-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># ...a &#39;regular&#39; number otherwise</span></span>
<span id="cb55-23"><a href="anova.html#cb55-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">formatC</span>(x, <span class="at">format =</span> <span class="st">&quot;f&quot;</span>, <span class="at">digits =</span> digits)</span>
<span id="cb55-24"><a href="anova.html#cb55-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb55-25"><a href="anova.html#cb55-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-26"><a href="anova.html#cb55-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-27"><a href="anova.html#cb55-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace e-notation by nicely formatted scientific notation (positive numbers)</span></span>
<span id="cb55-28"><a href="anova.html#cb55-28" aria-hidden="true" tabindex="-1"></a>x[<span class="fu">grepl</span>(<span class="st">&quot;e</span><span class="sc">\\</span><span class="st">+&quot;</span>, x)] <span class="ot">&lt;-</span> <span class="fu">paste0</span>(</span>
<span id="cb55-29"><a href="anova.html#cb55-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sub</span>(<span class="st">&quot;e</span><span class="sc">\\</span><span class="st">+&quot;</span>, <span class="st">&quot; </span><span class="sc">\\\\</span><span class="st">cdot 10^{&quot;</span>, x[<span class="fu">grepl</span>(<span class="st">&quot;e</span><span class="sc">\\</span><span class="st">+&quot;</span>, x)]), <span class="st">&quot;}&quot;</span></span>
<span id="cb55-30"><a href="anova.html#cb55-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-31"><a href="anova.html#cb55-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-32"><a href="anova.html#cb55-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace e-notation by nicely formatted scientific notation (negative numbers)</span></span>
<span id="cb55-33"><a href="anova.html#cb55-33" aria-hidden="true" tabindex="-1"></a>x[<span class="fu">grepl</span>(<span class="st">&quot;e</span><span class="sc">\\</span><span class="st">-&quot;</span>, x)] <span class="ot">&lt;-</span> <span class="fu">paste0</span>(</span>
<span id="cb55-34"><a href="anova.html#cb55-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sub</span>(<span class="st">&quot;e</span><span class="sc">\\</span><span class="st">-&quot;</span>, <span class="st">&quot; </span><span class="sc">\\\\</span><span class="st">cdot 10^{-&quot;</span>, x[<span class="fu">grepl</span>(<span class="st">&quot;e</span><span class="sc">\\</span><span class="st">-&quot;</span>, x)]), <span class="st">&quot;}&quot;</span></span>
<span id="cb55-35"><a href="anova.html#cb55-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-36"><a href="anova.html#cb55-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-37"><a href="anova.html#cb55-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove leading zeros (for example &quot;10^{03}&quot; --&gt; &quot;10^{3}&quot;)</span></span>
<span id="cb55-38"><a href="anova.html#cb55-38" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">&quot;</span><span class="sc">\\</span><span class="st">{0&quot;</span>, <span class="st">&quot;</span><span class="sc">\\</span><span class="st">{&quot;</span>, x)</span>
<span id="cb55-39"><a href="anova.html#cb55-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-40"><a href="anova.html#cb55-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove leading zeros (for example &quot;10^{-03}&quot; --&gt; &quot;10^{-3}&quot;)</span></span>
<span id="cb55-41"><a href="anova.html#cb55-41" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">&quot;</span><span class="sc">\\</span><span class="st">{-0&quot;</span>, <span class="st">&quot;</span><span class="sc">\\</span><span class="st">{-&quot;</span>, x)</span>
<span id="cb55-42"><a href="anova.html#cb55-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-43"><a href="anova.html#cb55-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Enclose the resulting strings in &quot;$&quot; so they will be rendered as math</span></span>
<span id="cb55-44"><a href="anova.html#cb55-44" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;$&quot;</span>, x, <span class="st">&quot;$&quot;</span>)</span>
<span id="cb55-45"><a href="anova.html#cb55-45" aria-hidden="true" tabindex="-1"></a>M[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> x</span>
<span id="cb55-46"><a href="anova.html#cb55-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-47"><a href="anova.html#cb55-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result as a table (use escape = FALSE to render math correctly)</span></span>
<span id="cb55-48"><a href="anova.html#cb55-48" aria-hidden="true" tabindex="-1"></a>caption <span class="ot">&lt;-</span> <span class="st">&quot;Post hoc comparison with Tukey correction for multiple testing.&quot;</span></span>
<span id="cb55-49"><a href="anova.html#cb55-49" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(M, <span class="at">escape =</span> <span class="cn">FALSE</span>, <span class="at">caption =</span> caption)</span></code></pre></div>
<p>The number of decimal points can be controlled with <code>digits</code> at the top.</p>
</details>
</details>
<details>
<summary>
Discussion
</summary>
<p><small><em>(In this section, you should not mention results, but the conclusions based on those results.)</em></small></p>
<p>If the test was significant <strong>and</strong> the difference large enough to be biologically relevant:</p>
<ul>
<li><font color = "green"><i class = "fa fa-check"></i></font> Consistent with existing literature, both thiazide and CCB appear to be effective at reducing blood pressure in young to middle-aged chronic hypertension patients;</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> A severe limitation of this comparison is the lack of a baseline measurement.<span class="math inline">\(^\dagger\)</span></li>
<li><font color = "red"><i class = "fa fa-times"></i></font> <em>(Overclaiming)</em> We have demonstrated that thiazide and CCB are effective at reducing systolic blood pressure in chronic hypertension patients.</li>
<li><font color = "red"><i class = "fa fa-times"></i></font> <em>(Overgeneralizing)</em> Thiazide and CCB appear to be effective at reducing blood pressure.</li>
</ul>
<p><small><span class="math inline">\(^\dagger\)</span>: For data with a baseline measurement, you should not use ANOVA, but a mixed model, because the observations are no longer independent.</small></p>
<p>If the test was insignificant <strong>or</strong> the difference too small to be biologically relevant:</p>
<ul>
<li><font color = "green"><i class = "fa fa-check"></i></font> <em>(If the study was sufficiently powerful)</em> Despite a fairly large sample size, we were unable to demonstrate a difference in systolic blood pressure. Hence, thiazide and CCB do not appear to be effective at reducing blood pressure in young to middle-aged chronic hypertension patients.</li>
<li><font color = "green"><i class = "fa fa-check"></i></font> <em>(If the study was underpowered)</em> We were unable to demonstrate a difference in systolic blood pressure, though this could be due to the limited sample size.</li>
<li><font color = "red"><i class = "fa fa-times"></i></font> <em>(Appeal to ignorance)</em> We have demonstrated the treatments to be ineffective.</li>
</ul>
<details>
<summary>
Why can’t I conclude there is no difference?
</summary>
<p>This is an inherent limitation of the <span class="math inline">\(p\)</span>-value. Under the null-hypothesis, any <span class="math inline">\(p\)</span>-value is as likely as any other (uniformity). Therefore, even if the <span class="math inline">\(p\)</span>-value is very large, this cannot be interpreted as evidence <em>for</em> the null-hypothesis.</p>
<p>For example, a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(0.20\)</span> is just as common a result as <span class="math inline">\(0.80\)</span> when the null-hypothesis is correct. The <span class="math inline">\(p\)</span>-value can <em>only</em> be used as evidence <em>against</em> the null-hypothesis (when it is small).</p>
<p>If you want to perform a test to find out whether the null-hypothesis is correct, what you are looking for is called an equivalence test. For <span class="math inline">\(t\)</span>-tests, this can be implemented easily through <a href="https://en.wikipedia.org/wiki/Equivalence_test#TOST_procedure">TOST</a>. An omnibus equivalence test can be constructed in a similar manner, by testing whether the <span class="math inline">\(F\)</span>-value is close enough to <span class="math inline">\(1\)</span>.</p>
</details>
</details>
<details>
<summary>
Generating citations
</summary>
<p>Any packages used in analysis should be cited in the methods section. The citations used here can be easily obtained as follows (note that this requires the packages to be installed):</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="anova.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>()        <span class="co"># Use this to cite R</span></span>
<span id="cb56-2"><a href="anova.html#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">RStudio.Version</span>() <span class="co"># Use this to cite RStudio</span></span>
<span id="cb56-3"><a href="anova.html#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>(<span class="st">&quot;car&quot;</span>)   <span class="co"># Use this to cite a package (here: car)</span></span></code></pre></div>
<p>You can add these entries to a reference manager (e.g., Zotero), or keep a BibTeX file yourself, as shown <a href="https://youtu.be/zuuOYjE8m98">here</a>.</p>
</details>
<details>
<summary>
Supplementary
</summary>
<p><small><em>(The following is not usually found in the main text, but can be included as supplementary material.)</em></small></p>
<p>Including diagnostic plots can be an effective way to convince the reader you considered the assumptions of the test or model used. It offers transparency and allows readers to judge for themselves whether they agree with your assessments and model choice.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-61"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-61-1.png" alt="(A) Normal quantile-quantile plot of the studentized residuals; (B) Scale-location plot." width="672" />
<p class="caption">
Figure 3.14: (A) Normal quantile-quantile plot of the studentized residuals; (B) Scale-location plot.
</p>
</div>
<p><em>If</em> you include any supplementary material, you should refer to it in the main text.</p>
</details>
<hr />

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body" line-spacing="2">
<div id="ref-car" class="csl-entry">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Fox, J. &amp; Weisberg, S. <em><a href="https://socialsciences.mcmaster.ca/jfox/Books/Companion/">An <span>R</span> companion to applied regression</a></em>. (Sage, 2019).</div>
</div>
<div id="ref-ShapiroSensitivities" class="csl-entry">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Royston, P. <a href="https://doi.org/10.1007/bf01891203">Approximating the shapiro-wilk w-test for non-normality</a>. <em>Statistics and Computing</em> <strong>2</strong>, 117–119 (1992).</div>
</div>
<div id="ref-R" class="csl-entry">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">R Core Team. <em><a href="https://www.R-project.org/">R: A language and environment for statistical computing</a></em>. (R Foundation for Statistical Computing, 2022).</div>
</div>
<div id="ref-RStudio" class="csl-entry">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">RStudio Team. <em><a href="http://www.rstudio.com/">RStudio: Integrated development environment for r</a></em>. (RStudio, PBC, 2022).</div>
</div>
<div id="ref-emmeans" class="csl-entry">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Lenth, R. V. <em><a href="https://CRAN.R-project.org/package=emmeans">Emmeans: Estimated marginal means, aka least-squares means</a></em>. (2022).</div>
</div>
<div id="ref-readxl" class="csl-entry">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Wickham, H. &amp; Bryan, J. <em><a href="https://CRAN.R-project.org/package=readxl">Readxl: Read excel files</a></em>. (2022).</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chi-squared-test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="twowaymultiway.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Tutorials.pdf", "Tutorials.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
