<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tutorial 10 Reading &amp; Storing Data | Statistics Tutorials &amp; Templates</title>
  <meta name="description" content="Tutorial 10 Reading &amp; Storing Data | Statistics Tutorials &amp; Templates" />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Tutorial 10 Reading &amp; Storing Data | Statistics Tutorials &amp; Templates" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tutorial 10 Reading &amp; Storing Data | Statistics Tutorials &amp; Templates" />
  
  
  

<meta name="author" content="Dr. F.J. Rodenburg © 2022" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exploration-pca.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics Tutorials & Templates</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>1</b> T-Test</a>
<ul>
<li class="chapter" data-level="1.1" data-path="t-test.html"><a href="t-test.html#read-t"><i class="fa fa-check"></i><b>1.1</b> Read the Data into R</a></li>
<li class="chapter" data-level="1.2" data-path="t-test.html"><a href="t-test.html#vis-t"><i class="fa fa-check"></i><b>1.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="1.3" data-path="t-test.html"><a href="t-test.html#choose-an-appropriate-t-test"><i class="fa fa-check"></i><b>1.3</b> Choose an Appropriate T-Test</a></li>
<li class="chapter" data-level="1.4" data-path="t-test.html"><a href="t-test.html#results-t"><i class="fa fa-check"></i><b>1.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="1.5" data-path="t-test.html"><a href="t-test.html#incorporating-this-in-a-paper"><i class="fa fa-check"></i><b>1.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chi-squared-test.html"><a href="chi-squared-test.html"><i class="fa fa-check"></i><b>2</b> Chi-Squared Test</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chi-squared-test.html"><a href="chi-squared-test.html#read-the-data-into-r"><i class="fa fa-check"></i><b>2.1</b> Read the Data into R</a></li>
<li class="chapter" data-level="2.2" data-path="chi-squared-test.html"><a href="chi-squared-test.html#vis-chi"><i class="fa fa-check"></i><b>2.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="2.3" data-path="chi-squared-test.html"><a href="chi-squared-test.html#conduct-a-chi-squared-test"><i class="fa fa-check"></i><b>2.3</b> Conduct a Chi-Squared Test</a></li>
<li class="chapter" data-level="2.4" data-path="chi-squared-test.html"><a href="chi-squared-test.html#results-chi"><i class="fa fa-check"></i><b>2.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="2.5" data-path="chi-squared-test.html"><a href="chi-squared-test.html#incorporating-this-in-a-paper-1"><i class="fa fa-check"></i><b>2.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>3</b> ANOVA</a>
<ul>
<li class="chapter" data-level="3.1" data-path="anova.html"><a href="anova.html#read-ANOVA"><i class="fa fa-check"></i><b>3.1</b> Read the Data into R</a>
<ul>
<li class="chapter" data-level="" data-path="anova.html"><a href="anova.html#reordering-a-factor"><i class="fa fa-check"></i>Reordering a Factor</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="anova.html"><a href="anova.html#vis-ANOVA"><i class="fa fa-check"></i><b>3.2</b> Visualize the Data</a></li>
<li class="chapter" data-level="3.3" data-path="anova.html"><a href="anova.html#analyze-the-data"><i class="fa fa-check"></i><b>3.3</b> Analyze the Data</a></li>
<li class="chapter" data-level="3.4" data-path="anova.html"><a href="anova.html#results-ANOVA"><i class="fa fa-check"></i><b>3.4</b> Correctly Phrase the Results</a></li>
<li class="chapter" data-level="3.5" data-path="anova.html"><a href="anova.html#incorporating-this-in-a-paper-2"><i class="fa fa-check"></i><b>3.5</b> Incorporating This in a Paper</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="twowaymultiway.html"><a href="twowaymultiway.html"><i class="fa fa-check"></i><b>4</b> Two-Way &amp; Multi-Way ANOVA</a></li>
<li class="chapter" data-level="5" data-path="linear-model.html"><a href="linear-model.html"><i class="fa fa-check"></i><b>5</b> Linear Model</a></li>
<li class="chapter" data-level="6" data-path="generalized-linear-model.html"><a href="generalized-linear-model.html"><i class="fa fa-check"></i><b>6</b> Generalized Linear Model</a></li>
<li class="chapter" data-level="7" data-path="mixed-model.html"><a href="mixed-model.html"><i class="fa fa-check"></i><b>7</b> Mixed Model</a></li>
<li class="chapter" data-level="8" data-path="glmm.html"><a href="glmm.html"><i class="fa fa-check"></i><b>8</b> GLMM</a></li>
<li class="chapter" data-level="9" data-path="exploration-pca.html"><a href="exploration-pca.html"><i class="fa fa-check"></i><b>9</b> Exploration: PCA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="exploration-pca.html"><a href="exploration-pca.html#read-the-data-into-r-1"><i class="fa fa-check"></i><b>9.1</b> Read the Data into R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reading-storing-data.html"><a href="reading-storing-data.html"><i class="fa fa-check"></i><b>10</b> Reading &amp; Storing Data</a>
<ul>
<li class="chapter" data-level="10.1" data-path="reading-storing-data.html"><a href="reading-storing-data.html#tidy"><i class="fa fa-check"></i><b>10.1</b> Tidy Format</a></li>
<li class="chapter" data-level="10.2" data-path="reading-storing-data.html"><a href="reading-storing-data.html#separate-data-entry-analysis"><i class="fa fa-check"></i><b>10.2</b> Separate Data Entry &amp; Analysis</a>
<ul>
<li class="chapter" data-level="" data-path="reading-storing-data.html"><a href="reading-storing-data.html#excel-is-not-statistical-software"><i class="fa fa-check"></i>Excel Is Not Statistical Software</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="reading-storing-data.html"><a href="reading-storing-data.html#metadata"><i class="fa fa-check"></i><b>10.3</b> Meta Data</a></li>
<li class="chapter" data-level="10.4" data-path="reading-storing-data.html"><a href="reading-storing-data.html#csv"><i class="fa fa-check"></i><b>10.4</b> Reading Data as CSV</a></li>
<li class="chapter" data-level="10.5" data-path="reading-storing-data.html"><a href="reading-storing-data.html#Excel"><i class="fa fa-check"></i><b>10.5</b> Reading Data from Excel</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics Tutorials &amp; Templates</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="reading-storing-data" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Tutorial 10</span> Reading &amp; Storing Data<a href="reading-storing-data.html#reading-storing-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><i><small>This chapter provides some advice for how to store data and shows you various ways in which you can read it.</i></small></p>
<hr />
<details>
<summary>
Summary
</summary>
<ul>
<li><strong>Store data in <a href="https://r4ds.had.co.nz/tidy-data.html#fig:tidy-structure">tidy format</a></strong>. There are exceptions to this format, but only one for the methods listed on this website; <small>(namely, <a href="https://stefvanbuuren.name/fimd/sec-longandwide.html">long-format</a> for time series)</small></li>
<li><strong>Separate data <em>entry</em> and <em>analysis</em></strong>. Excel invites you to do questionable things, like adding figures and explanation to raw data. Don’t do this. Never edit or clutter raw data. If you must use Excel for data exploration, create a separate file for this purpose.</li>
<li><strong>Use short, informative variable names</strong>, using only lower- and uppercase letters, numbers,<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> and if needed periods (.) or underscores (_). Do not add the unit of measurement, or any explanation. This belongs in the meta data. If variable names are still long, consider using abbreviations. Avoid special characters (!@#$%^&amp;*-a=+,&lt;&gt;?/).</li>
<li><strong>Keep a <a href="reading-storing-data.html#metadata">meta data</a> file</strong>, or sheet, that explains variables, abbreviations, unit of measurement, etc. See <a href="https://docs.google.com/spreadsheets/d/1dcblrkYrCO5lz7akSCkguYSWHfGxfJh2f6Pg2B8Q9ck/edit#gid=322816193">here</a> for an example. This also helps keep variable names short and free of special characters.</li>
<li><strong>Save data as comma-separated values</strong> (.csv), rather than as an Excel file (.xlsx). Saving into this format automatically removes any content statistical software cannot read anyway, like figures and coloring. This file format is suitable for most sizes of data commonly encountered in the life sciences (anything that still fits into RAM on an ordinary computer).</li>
</ul>
</details>
<div id="tidy" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> Tidy Format<a href="reading-storing-data.html#tidy" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Collect data in a simple, consistent format called <em>tidy data</em>,<span class="citation"><sup><a href="#ref-tidy" role="doc-biblioref">7</a></sup></span> such that minimal effort is required to clean the data once you get to the analysis: Rows represent observations, columns represent the variables measured for those observations:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-100"></span>
<img src="Tutorials_files/figure-html/unnamed-chunk-100-1.png" alt="The basic principle of tidy data. This data set has 5 observations of 4 variables." width="672" />
<p class="caption">
Figure 10.1: The basic principle of tidy data. This data set has 5 observations of 4 variables.
</p>
</div>
<details>
<summary>
Good example
</summary>
<p>The <code>iris</code> data set (preinstalled with R) is in tidy format:</p>
<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-101">Table 10.1: </span>The first 5 rows of the <tt>iris</tt> data set. Each row is a flower and each column a property.
</caption>
<thead>
<tr>
<th style="text-align:center;">
Sepal.Length
</th>
<th style="text-align:center;">
Sepal.Width
</th>
<th style="text-align:center;">
Petal.Length
</th>
<th style="text-align:center;">
Petal.Width
</th>
<th style="text-align:center;">
Species
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
5.1
</td>
<td style="text-align:center;">
3.5
</td>
<td style="text-align:center;">
1.4
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
setosa
</td>
</tr>
<tr>
<td style="text-align:center;">
4.9
</td>
<td style="text-align:center;">
3.0
</td>
<td style="text-align:center;">
1.4
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
setosa
</td>
</tr>
<tr>
<td style="text-align:center;">
4.7
</td>
<td style="text-align:center;">
3.2
</td>
<td style="text-align:center;">
1.3
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
setosa
</td>
</tr>
<tr>
<td style="text-align:center;">
4.6
</td>
<td style="text-align:center;">
3.1
</td>
<td style="text-align:center;">
1.5
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
setosa
</td>
</tr>
<tr>
<td style="text-align:center;">
5.0
</td>
<td style="text-align:center;">
3.6
</td>
<td style="text-align:center;">
1.4
</td>
<td style="text-align:center;">
0.2
</td>
<td style="text-align:center;">
setosa
</td>
</tr>
<tr>
<td style="text-align:center;">
…
</td>
<td style="text-align:center;">
…
</td>
<td style="text-align:center;">
…
</td>
<td style="text-align:center;">
…
</td>
<td style="text-align:center;">
…
</td>
</tr>
</tbody>
</table>
<p>Here, the rows each represent one observation (a distinct flower), and the columns represent the variables measured/recorded (physical dimensions and species).</p>
</details>
<details>
<summary>
Bad example
</summary>
<p>A common deviation from tidy format is to represent groups as columns:</p>
<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-102">Table 10.2: </span>Systolic blood pressure (SBP) of 10 individuals. <font color="red">(untidy)</font>
</caption>
<thead>
<tr>
<th style="text-align:center;">
women
</th>
<th style="text-align:center;">
men
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
114
</td>
<td style="text-align:center;">
123
</td>
</tr>
<tr>
<td style="text-align:center;">
121
</td>
<td style="text-align:center;">
117
</td>
</tr>
<tr>
<td style="text-align:center;">
125
</td>
<td style="text-align:center;">
117
</td>
</tr>
<tr>
<td style="text-align:center;">
108
</td>
<td style="text-align:center;">
117
</td>
</tr>
<tr>
<td style="text-align:center;">
122
</td>
<td style="text-align:center;">
116
</td>
</tr>
</tbody>
</table>
<p>Do you have different groups? Time points? Replicates of the experiment? Then try to adhere to the same principle: Columns are variables. Simply add a variable that indicates which group/time point/replicate this observation belongs to:</p>
<table class="table" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-103">Table 10.3: </span>Sex and systolic blood pressure (SBP) of 10 individuals. <font color="blue">(tidy)</font>
</caption>
<thead>
<tr>
<th style="text-align:center;">
sex
</th>
<th style="text-align:center;">
SBP
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
114
</td>
</tr>
<tr>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
121
</td>
</tr>
<tr>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
125
</td>
</tr>
<tr>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
108
</td>
</tr>
<tr>
<td style="text-align:center;">
female
</td>
<td style="text-align:center;">
122
</td>
</tr>
<tr>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
123
</td>
</tr>
<tr>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
117
</td>
</tr>
<tr>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
117
</td>
</tr>
<tr>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
117
</td>
</tr>
<tr>
<td style="text-align:center;">
male
</td>
<td style="text-align:center;">
116
</td>
</tr>
</tbody>
</table>
</details>
<details>
<summary>
Converting to tidy format
</summary>
<p>If you have data split by group/time point/replicate here is how you can convert it to tidy format:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="reading-storing-data.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The untidy data set</span></span>
<span id="cb90-2"><a href="reading-storing-data.html#cb90-2" aria-hidden="true" tabindex="-1"></a>Untidy</span></code></pre></div>
<pre><code>##   women men
## 1   114 123
## 2   121 117
## 3   125 117
## 4   108 117
## 5   122 116</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="reading-storing-data.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert by hand</span></span>
<span id="cb92-2"><a href="reading-storing-data.html#cb92-2" aria-hidden="true" tabindex="-1"></a>Tidy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb92-3"><a href="reading-storing-data.html#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>), <span class="at">each =</span> <span class="fu">nrow</span>(Untidy)),</span>
<span id="cb92-4"><a href="reading-storing-data.html#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">SBP =</span> <span class="fu">c</span>(Untidy<span class="sc">$</span>women, Untidy<span class="sc">$</span>men)</span>
<span id="cb92-5"><a href="reading-storing-data.html#cb92-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb92-6"><a href="reading-storing-data.html#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="reading-storing-data.html#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert using a package (install if missing)</span></span>
<span id="cb92-8"><a href="reading-storing-data.html#cb92-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;reshape2&quot;</span>)</span>
<span id="cb92-9"><a href="reading-storing-data.html#cb92-9" aria-hidden="true" tabindex="-1"></a><span class="fu">melt</span>(Untidy)</span></code></pre></div>
<pre><code>##    variable value
## 1     women   114
## 2     women   121
## 3     women   125
## 4     women   108
## 5     women   122
## 6       men   123
## 7       men   117
## 8       men   117
## 9       men   117
## 10      men   116</code></pre>
<p>If you have a simple data set like the one shown here, converting with the package <code>reshape2</code> is easiest. Converting by hand may be slightly more work, but I prefer it because you can easily see what’s going on, add more variables if needed, etc.</p>
</div>
<div id="separate-data-entry-analysis" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Separate Data Entry &amp; Analysis<a href="reading-storing-data.html#separate-data-entry-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Spreadsheet software like Excel or Google Sheets is great for easy data entry. A well-designed spreadsheet can even partially protect against errors, by limiting what values are allowed in certain columns (e.g., how <code>Species</code> is restricted <a href="https://docs.google.com/spreadsheets/d/1dcblrkYrCO5lz7akSCkguYSWHfGxfJh2f6Pg2B8Q9ck/edit?pli=1#gid=1478490863">here</a>).<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<details>
<summary>
Beware ‘intelligent’ conversions
</summary>
<p>Programming requires exact precision in syntax, which can be very frustrating for beginners. To address this, many programs try to intelligently interpret your input:</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-105"></span>
<img src="figures/typo.png" alt="My hasty attempt to figure out which clothes to wear to work." width="100%" />
<p class="caption">
Figure 10.2: My hasty attempt to figure out which clothes to wear to work.
</p>
</div>
<p>While this usually a good thing, Excel does many such corrections without notice, and some even irreversibly. This can have serious repercussions for scientific research. For example, a 2016 article found widespread errors in gene names due to autocorrected Excel input.<span class="citation"><sup><a href="#ref-genenameerrors" role="doc-biblioref">8</a></sup></span> Always check whether your input is correctly interpreted, or change the data type to “text” instead of “general” for everything you enter.</p>
</details>
<p>Once the data are correctly entered into some spreadsheet software (Excel, Google Sheets), this is where the data entry ends. Do not add any markup, coloring, notes, figures, or tables.</p>
<p>As a general principle, <strong>raw data should never be edited</strong>, nor should it be cluttered with additional information. This does not belong in your raw data, but either in a <a href="reading-storing-data.html#metadata">meta data</a> file, or in some separate file for analysis that takes the raw data file as input.</p>
<p>Some additional guidelines for tidy data entry include:</p>
<ul>
<li>Avoid empty rows or columns for spacing, start at row 1, column 1;</li>
<li>Avoid the ‘merge cells’ option, this breaks the row/column format;</li>
<li>Limit a spreadsheet to one data set. Adding multiple data sets to one sheet may look like you have more oversight in <em>Excel</em>, but it makes any downstream analysis more convoluted.</li>
</ul>
<div id="excel-is-not-statistical-software" class="section level3 unnumbered hasAnchor">
<h3>Excel Is Not Statistical Software<a href="reading-storing-data.html#excel-is-not-statistical-software" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Even if you do create a separate file to explore/analyze your data, I still advice against using Excel for this, for the following reasons:</p>
<details>
<summary>
A history of inaccuracies
</summary>
<p>Excel has long been a program ridden with computational inaccuracies and slow to correct its mistakes.</p>
<p>Non-trivial errors in the calculation of discrete probability distributions, as well as severe limitations of its random number generator (<code>RAND()</code>) were found in Excel 1997,<span class="citation"><sup><a href="#ref-Excel1997a" role="doc-biblioref">9</a>,<a href="#ref-Excel1997b" role="doc-biblioref">10</a></sup></span> exacerbated in Excel 2000/XP,<span class="citation"><sup><a href="#ref-Excel2000" role="doc-biblioref">11</a></sup></span> and only partially addressed in Excel 2003, while simultaneously introducing new problems.<span class="citation"><sup><a href="#ref-Excel2003a" role="doc-biblioref">12</a>,<a href="#ref-Excel2003b" role="doc-biblioref">13</a></sup></span> Perhaps unsurprisingly then, Excel 2007 still failed some of the same accuracy tests in use since 1998.<span class="citation"><sup><a href="#ref-Excel2007" role="doc-biblioref">14</a></sup></span></p>
<p>By the time Excel 2010 was released, persisting issues with the computation of probabilities and quantiles had been addressed, and the <code>RAND()</code> function had improved.<span class="citation"><sup><a href="#ref-Excel2010" role="doc-biblioref">15</a></sup></span> Nevertheless, the authors of a paper reviewing Excel 2010 concluded:</p>
<blockquote>
<p>[W]ithout a prompt reaction from Microsoft, the already very critical view against using spreadsheets for doing any statistical analysis […] will be even more justified. <strong>It is standard practice for software developers to fix errors quickly and correctly. Microsoft has fixed the errors in the statistical procedures of Excel neither quickly nor correctly.</strong> The recent improvements reported in this paper should not hide the fact that Microsoft is still marketing a product that contains known errors.</p>
</blockquote>
<p>I have emphasized the part that summarizes this section. Excel is proprietary software from a developer that cares little for its statistical accuracy. In contrast, R, Python, Julia and the likes are free &amp; open source (meaning anyone can view the source code).</p>
<p>Few new articles have since been published on this issue—presumably because R and Python have since become the <em>de facto</em> industry standard for statistical analysis.</p>
</details>
<details>
<summary>
Lack of serious modeling options
</summary>
<p>If statistics were a toolbox, then Excel would be a hammer. Yes, you can do a lot with it, but if you’re trying to cut something in half, or insert a screw, maybe use a different tool. Excel has add-ins, but these are neither open source, nor curated.</p>
<p>As of writing, R has 18,834 free, open source packages, offering anything from statistical tests, models, machine learning, visualization (<code>base</code>, <code>ggplot2</code>, <code>plotly</code>), literate programming (<code>rmarkdown</code>, <code>quarto</code>), presentations (e.g., <code>xaringan</code>), paper writing (<code>rticles</code>), book authoring (<code>bookdown</code>), app and dashboard development (<code>shiny</code>), and even interfaces to state-of-the-art deep learning frameworks (e.g., <code>tensorflow</code>, <code>keras</code>).</p>
</details>
<details>
<summary>
Computations are opaque
</summary>
<p>Analyses performed in Excel consist of cells with formulas referring to other (ranges of) cells. This is not a problem for simple operations, like adding or subtracting two columns. But in actual analysis, there will be many such steps, and Excel ‘code’ becomes much harder to read than other programming languages, since you can only view the contents of one cell at a time.</p>
<p>The worst offenders are large Excel sheets with both data and computations, requiring not only that you trace back the operations performed in multiple cells, but also that you scroll between (often distant) locations in the sheet. Bugs <em>will</em> appear in large analyses and it is needlessly difficult to trace the origin of mistakes.</p>
</details>
<p>Excel is also slow, especially in files combining data and analysis; it is paid software, requiring a license; and its ‘arrange cells however you see fit’ approach, makes analyses much harder to reproduce.</p>
<p>If you want an easy interface to enter your data, Excel is great software. Any elaborate analyses in Excel though, are inefficient at best and severely limited at worst.</p>
</div>
</div>
<div id="metadata" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Meta Data<a href="reading-storing-data.html#metadata" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To help keep variable names short, to include the unit of measurement, to explain how something was measured, or to provide other relevant comments about the data, you can keep a meta data file (or sheet). An example can be found <a href="https://docs.google.com/spreadsheets/d/1dcblrkYrCO5lz7akSCkguYSWHfGxfJh2f6Pg2B8Q9ck/edit?pli=1#gid=322816193">here</a>.</p>
<p>Meta data means <em>data about data</em>. If you take a picture with your phone, meta data contains information about how the picture was taken (shutter time, ISO, etc.), or where the picture was taken. Naturally, you do not want this information pasted onto the picture itself. In a similar vein, you should not include comments about the data, in the raw data itself. This is why you should keep a separate file for meta data.</p>
</div>
<div id="csv" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Reading Data as CSV<a href="reading-storing-data.html#csv" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<details>
<summary>
Why this format?
</summary>
<p>Saving into CSV format automatically removes any content statistical software cannot read anyway, like figures and coloring. This file format is suitable for most sizes of data commonly encountered in the life sciences (anything that still fits into RAM on an ordinary computer).</p>
<p>For very large data sets, there are special high-performance file types, like <a href="https://en.wikipedia.org/wiki/Hierarchical_Data_Format#HDF5">HDF5</a> or <a href="https://en.wikipedia.org/wiki/Apache_Parquet">parquet</a>. However, these offer little to no benefit for the small-sized data sets used in the tutorials here.</p>
</details>
<details>
<summary>
Setting up your working directory
</summary>
<ul>
<li>Save the data in a folder;</li>
<li>Open RStudio and create a new R markdown file; <small>(<strong>File</strong> &gt; <strong>New File</strong> &gt; <strong>R Markdown</strong>)</small></li>
<li>Save your R markdown file to the same location as the data;</li>
<li>Set working directory to source file location. <small>(<strong>Session</strong> &gt; <strong>Set Working Directory</strong> &gt; <strong>To Source File Location</strong>)</small></li>
</ul>
</details>
<p>Provided your working directory is set up correctly, you can read CSV files as follows:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="reading-storing-data.html#cb94-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;NameOfYourFile.csv&quot;</span>)</span></code></pre></div>
<p>Here, <code>DF</code> is an arbitrary name. I use it because it is short (you will be typing this name a lot) and because it is an abbreviation of ‘data frame’, so it keeps code easy to read for others and your future self.</p>
<p>To check that your data has been read correctly by the software, try one of the following:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="reading-storing-data.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DF)</span>
<span id="cb95-2"><a href="reading-storing-data.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DF)</span>
<span id="cb95-3"><a href="reading-storing-data.html#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(DF)</span>
<span id="cb95-4"><a href="reading-storing-data.html#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(DF)</span></code></pre></div>
<details>
<summary>
What it should look like
</summary>
<p>The <code>str</code> function displays the structure of the object. In case your file is in tidy format and read correctly, it will look something like this:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="reading-storing-data.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(iris)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<details>
<summary>
More explanation
</summary>
<p>The first line tells us this object is a <code>data.frame</code> consisting of 150 observations (rows) and 5 variables (columns). It then tells us what kind of information those variables contain:</p>
<ul>
<li><code>num</code>: Numeric (any number, stored as a <a href="https://youtu.be/L8OYx1I8qNg">floating point</a>)</li>
<li><code>int</code>: Integer (whole number)</li>
<li><code>chr</code>: Character string</li>
<li><code>Factor</code>: Categorical variable with a fixed number of levels</li>
<li>Some <a href="https://adv-r.hadley.nz/vectors-chap.html#s3-atomic-vectors">less common ones</a>.</li>
</ul>
<p>In the example shown here, the data has been read correctly, because numbers show as <code>num</code> and the flower species shows as <code>Factor</code>. If your factor shows up as a character (<code>chr</code>), you can convert it as follows:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="reading-storing-data.html#cb98-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>x <span class="ot">&lt;-</span> <span class="fu">factor</span>(DF<span class="sc">$</span>x)</span></code></pre></div>
Where <code>x</code> is the name of the variable you want to convert to factor.
</details>
<p>The <code>summary</code> shows some summary statistics for numeric variables, and counts of categories for factors:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="reading-storing-data.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<details>
<summary>
More explanation
</summary>
<p>For numeric variables, the minimum, first 25%, first 50% (median), the mean (average), first 75% and the maximum are shown. This provides some basic indication of the distribution of the data, and it may point to potential outliers if the minimum or maximum are unrealistically far away.</p>
<p>For factors, the counts of categories are useful to see whether the data are balanced (same number of observations per category).</p>
</details>
<p>Finally, <code>head</code> and <code>tail</code> show the first and last rows of the data, respectively (6 rows by default):</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="reading-storing-data.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="reading-storing-data.html#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(iris)</span></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 145          6.7         3.3          5.7         2.5 virginica
## 146          6.7         3.0          5.2         2.3 virginica
## 147          6.3         2.5          5.0         1.9 virginica
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica</code></pre>
</details>
<details>
<summary>
My output looks different
</summary>
<p>First, make sure your data are in <a href="reading-storing-data.html#tidy">tidy format</a>. That also means no empty rows before your data starts, no comments in cells where there is no data, etc.</p>
<p>If you’re sure your data is in the right format, another very common issue is the <strong>decimal separator</strong>. In some countries (including The Netherlands), decimal numbers are separated with a comma, e.g.:</p>
<p><span class="math display">\[\begin{aligned}\text{Dutch style:} \quad 3 &amp;- 0{,}1 = 2{,}9 \\
\text{English style:} \quad 3 &amp;- 0.1 = 2.9
\end{aligned}\]</span></p>
<p>If you have a Dutch version of Excel, then CSV files are actually not separated by commas but semi-colons, because the software would otherwise not be able to tell new numbers and decimal numbers apart.</p>
<p>The solution for this is fortunately very simple, use <tt>read.csv<b>2</b></tt>:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="reading-storing-data.html#cb105-1" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;NameOfYourFile.csv&quot;</span>)</span></code></pre></div>
<p>If this too does not solve your problem, try copying the entire error message and searching for it online. Usually, there will have been someone else with the same problem on <a href="stackoverflow.com">StackOverflow</a>, so you can try the solutions offered there.</p>
</details>
</div>
<div id="Excel" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Reading Data from Excel<a href="reading-storing-data.html#Excel" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Reading data directly from Excel only works if R ‘understands’ the file. An Excel file cluttered with figures or special functionality will not be readable, which is why I recommend just using <a href="https://youtu.be/BGUqZc-Pb8w">CSV</a> instead. Despite the drawbacks, experience shows that many people prefer to read data directly from Excel anyway, so I will demonstrate this too.</p>
<details>
<summary>
Setting up your working directory
</summary>
<ul>
<li>Save the data in a folder;</li>
<li>Open RStudio and create a new R markdown file; <small>(<strong>File</strong> &gt; <strong>New File</strong> &gt; <strong>R Markdown</strong>)</small></li>
<li>Save your R markdown file to the same location as the data;</li>
<li>Set working directory to source file location. <small>(<strong>Session</strong> &gt; <strong>Set Working Directory</strong> &gt; <strong>To Source File Location</strong>)</small></li>
</ul>
</details>
<p>Provided your working directory is set up correctly, there are many ways to directly read your Excel file into R, for example:</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="reading-storing-data.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using readxl</span></span>
<span id="cb106-2"><a href="reading-storing-data.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;readxl&quot;</span>)</span>
<span id="cb106-3"><a href="reading-storing-data.html#cb106-3" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;NameOfYourFile.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="dv">1</span>)</span>
<span id="cb106-4"><a href="reading-storing-data.html#cb106-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-5"><a href="reading-storing-data.html#cb106-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Using xlsx</span></span>
<span id="cb106-6"><a href="reading-storing-data.html#cb106-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;xlsx&quot;</span>)</span>
<span id="cb106-7"><a href="reading-storing-data.html#cb106-7" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">read.xlsx</span>(<span class="st">&quot;NameOfYourFile.xlsx&quot;</span>, <span class="at">sheetIndex =</span> <span class="dv">1</span>)</span>
<span id="cb106-8"><a href="reading-storing-data.html#cb106-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-9"><a href="reading-storing-data.html#cb106-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Using fread</span></span>
<span id="cb106-10"><a href="reading-storing-data.html#cb106-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>)</span>
<span id="cb106-11"><a href="reading-storing-data.html#cb106-11" aria-hidden="true" tabindex="-1"></a>DF <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="at">file =</span> <span class="st">&quot;NameOfYourFile.xlsx&quot;</span>)</span></code></pre></div>
<p>If you are already familiar with the syntax of one of these packages, there is no need to switch. If people send me Excel sheets, I usually use <code>readxl</code>. A more general and high-performance function is <code>fread</code> from the package <code>data.table</code>.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body" line-spacing="2">
<div id="ref-tidy" class="csl-entry">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Wickham, H. <a href="https://doi.org/10.18637/jss.v059.i10">Tidy data</a>. <em>Journal of Statistical Software</em> <strong>59</strong>, (2014).</div>
</div>
<div id="ref-genenameerrors" class="csl-entry">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Ziemann, M., Eren, Y. &amp; El-Osta, A. <a href="https://doi.org/10.1186/s13059-016-1044-7">Gene name errors are widespread in the scientific literature</a>. <em>Genome Biology</em> <strong>17</strong>, (2016).</div>
</div>
<div id="ref-Excel1997a" class="csl-entry">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Knüsel, L. <a href="https://doi.org/10.1016/s0167-9473(97)81756-2">On the accuracy of statistical distributions in microsoft excel 97</a>. <em>Computational Statistics <span>&amp;</span> Data Analysis</em> <strong>26</strong>, 375–377 (1998).</div>
</div>
<div id="ref-Excel1997b" class="csl-entry">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">McCullough, B. D. &amp; Wilson, B. <a href="https://doi.org/10.1016/s0167-9473(99)00004-3">On the accuracy of statistical procedures in microsoft excel 97</a>. <em>Computational Statistics <span>&amp;</span> Data Analysis</em> <strong>31</strong>, 27–37 (1999).</div>
</div>
<div id="ref-Excel2000" class="csl-entry">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">McCullough, B. D. &amp; Wilson, B. On the accuracy of statistical procedures in microsoft excel 2000 and excel XP. <em>Computational Statistics &amp; Data Analysis</em> <strong>40</strong>, 713–721 (2002).</div>
</div>
<div id="ref-Excel2003a" class="csl-entry">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">McCullough, B. D. &amp; Wilson, B. <a href="https://doi.org/10.1016/j.csda.2004.06.016">On the accuracy of statistical procedures in microsoft excel 2003</a>. <em>Computational Statistics <span>&amp;</span> Data Analysis</em> <strong>49</strong>, 1244–1252 (2005).</div>
</div>
<div id="ref-Excel2003b" class="csl-entry">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Knüsel, L. <a href="https://doi.org/10.1016/j.csda.2004.02.008">On the accuracy of statistical distributions in microsoft excel 2003</a>. <em>Computational Statistics <span>&amp;</span> Data Analysis</em> <strong>48</strong>, 445–449 (2005).</div>
</div>
<div id="ref-Excel2007" class="csl-entry">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">McCullough, B. D. &amp; Heiser, D. A. <a href="https://doi.org/10.1016/j.csda.2008.03.004">On the accuracy of statistical procedures in microsoft excel 2007</a>. <em>Computational Statistics <span>&amp;</span> Data Analysis</em> <strong>52</strong>, 4570–4578 (2008).</div>
</div>
<div id="ref-Excel2010" class="csl-entry">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Mélard, G. <a href="https://doi.org/10.1007/s00180-014-0482-5">On the accuracy of statistical procedures in microsoft excel 2010</a>. <em>Computational Statistics</em> <strong>29</strong>, 1095–1128 (2014).</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p><small>When using numbers, keep in mind that R does not accept variable names <em>starting</em> with a number. R will automatically <a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/make.names">convert</a> these.</small><a href="reading-storing-data.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p><small>In Google Sheets, you can do this by going to <strong>Data</strong> &gt; <strong>Data validation</strong>.</small><a href="reading-storing-data.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exploration-pca.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Tutorials.pdf", "Tutorials.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
